// The agent interface for scripts: one call per run, one JSON object on stdout (docs/agent-interface.md).
// Technical log rows and progress go to stderr; neither carries story text.
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';
import { loadAgentConfig } from './config.ts';
import { openAgent, underLock } from './agent-api.ts';
import type { AgentApi, AgentResponse } from './agent-api.ts';
import type { Log } from './model-error.ts';
import { safeErrorDetails } from './model-error.ts';

// Arguments are the client's JSON; the core checks every field it reads.
type Args = { [field: string]: unknown };
// A writer holds the library lock for the whole run: a turn is generated by the process that started it, so start_story
// and act stay in the foreground until the turn ends. Readers only look at the journal and may run beside a writer.
const WRITERS: Record<string, (api: AgentApi, args: Args) => AgentResponse | Promise<AgentResponse>> = {
  create_seed: (api, args) => api.createSeed(args),
  start_story: async (api, args) => untilSettled(api, await api.startStory({ ...args, wait: 600 })),
  act: async (api, args) => untilSettled(api, await api.act({ ...args, wait: 600 })),
  fork: (api, args) => api.fork(args),
};
const READERS: Record<string, (api: AgentApi, args: Args) => AgentResponse | Promise<AgentResponse>> = {
  read: (api, args) => api.read(args), status: (api, args) => api.status(args), wait: (api, args) => api.wait(args),
};
const USAGE = `Usage: node local/agent-cli.ts <${[...Object.keys(WRITERS), ...Object.keys(READERS)].join('|')}> [--json '{...}' | --json -] [--agent id]`;

async function untilSettled(api: AgentApi, response: AgentResponse) {
  while (response.status === 'running' && response.requestId) response = await api.wait({ requestId: response.requestId, seconds: 600 });
  return response;
}
const print = (response: AgentResponse) => process.stdout.write(JSON.stringify(response) + '\n');
const log: Log = (event, code, details) => process.stderr.write(JSON.stringify({ at: new Date().toISOString(), event,
  ...(typeof code === 'string' && /^[a-z_]{1,40}$/.test(code) ? { code } : {}), ...safeErrorDetails(details) }) + '\n');

process.umask(0o077);
let parsed;
try {
  parsed = parseArgs({ allowPositionals: true, options: { json: { type: 'string' }, agent: { type: 'string' } } });
} catch { parsed = null; }
const command = parsed?.positionals.length === 1 ? parsed.positionals[0] : '';
const writer = Object.hasOwn(WRITERS, command);
let args: Args | null = null;
try {
  const text = parsed?.values.json === '-' ? readFileSync(0, 'utf8') : parsed?.values.json ?? '{}';
  const value: unknown = JSON.parse(text);
  if (value && typeof value === 'object' && !Array.isArray(value)) args = value as Args;
} catch {}
if (!parsed || (!writer && !Object.hasOwn(READERS, command)) || !args) {
  console.error(USAGE);
  print({ status: 'failed', reason: 'invalid_request' });
  process.exitCode = 2;
} else {
  try {
    const config = loadAgentConfig();
    if (!writer && !existsSync(config.dbPath)) print({ status: 'failed', reason: 'not_found' });
    else if (!writer || underLock(config.dbPath, fileURLToPath(import.meta.url), () => print({ status: 'busy', reason: 'library_locked' }))) {
      const agent = await openAgent(config, { userId: parsed.values.agent, readOnly: !writer, log,
        onProgress: (requestId, status) => process.stderr.write(JSON.stringify({ event: 'compaction', stage: status.stage }) + '\n') });
      // A signal ends the turn as interrupted, with the point it saved; the pending wait then returns that receipt.
      for (const signal of ['SIGTERM', 'SIGINT'] as const) process.on(signal, () => { void agent.api.close(); });
      try {
        const response = await (writer ? WRITERS : READERS)[command](agent.api, args);
        print(response);
        process.exitCode = response.status === 'done' || response.status === 'running' ? 0 : 1;
      } finally { await agent.close(); }
    }
  } catch (error) {
    // Configuration and startup errors are this project's own messages, never provider output.
    console.error((error as Error).message);
    print({ status: 'failed', reason: 'internal_error' });
    process.exitCode = 1;
  }
}
