// English interface catalog. Keys, arguments and the notes for translators are in ru.ts, which defines `Messages`.

import type { Messages } from './ru.ts';

const count = (n: number, one: string, many: string, shown = String(n)) => `${shown} ${n === 1 ? one : many}`;
const grouped = (n: number) => String(Math.round(n)).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
const lastScenes = (n: number | null) => (n === null ? 'the latest scenes' : `the latest ${count(n, 'scene', 'scenes')}`);
const jobs = (n: number | null) => (n === null ? 'unknown' : String(n));

export const en: Messages = {
  format: {
    number: n => grouped(n),
    quote: text => `“${text}”`,
    untitled: 'untitled',
    untitledButton: 'Untitled',
    unknown: 'unknown',
  },

  count: {
    scenes: n => count(n, 'scene', 'scenes'),
    stories: n => count(n, 'story', 'stories'),
    branches: n => count(n, 'branch', 'branches'),
    checkpoints: n => count(n, 'checkpoint', 'checkpoints'),
    parts: n => count(n, 'part', 'parts'),
    characters: n => count(n, 'character', 'characters'),
  },

  duration: {
    seconds: s => `${s} s`,
    minutes: (m, ss) => `${m} min ${ss} s`,
    hours: (h, mm) => `${h} h ${mm} min`,
  },

  buttons: {
    menu: '🏠 Menu',
    continue: '▶️ Continue',
    stop: '✖️ Stop',
    lastScene: '📄 Last scene',
    context: '📏 Context',
    model: '🤖 Model',
    checkpoints: '🔖 Checkpoints',
    branches: '🌿 Branches',
    seeds: '📚 Seeds',
    seedsCount: n => `📚 Seeds (${n})`,
    newSeed: '➕ New seed',
    refresh: '🔄 Refresh',
    compactNow: '🗜 Compact now',
    cancelScene: '✖️ Cancel generation',
    cancelCompaction: '✖️ Cancel compaction',
    toCheckpoint: '◀️ Back to checkpoint',
    previous: '⬅️ Previous',
    next: 'Next ➡️',
    keep: '↩️ Keep it',
    pictureStyle: '🎨 Picture style',
  },

  common: {
    current: '✅ current',
    page: (page, pages) => `Page ${page} of ${pages}`,
    storyName: (title, n) => `${title} · story ${n}`,
    noScenes: 'no scenes yet',
    staleHint: 'It may have been deleted, or this screen is out of date.',
    failure: '⚠️ Could not show this screen.',
    failureHint: 'Go back to the menu and try again.',
    whatIsSeed: 'A seed is a world, a character and an opening situation. One seed can start any number of stories.',
  },

  busy: {
    scene: {
      startOrDeleteSeed: '⏳ A scene is being written: you can start a story or delete the seed once it is done.',
      switchOrDeleteBranch: '⏳ A scene is being written: you can switch or delete branches once it is done.',
      fork: '⏳ A scene is being written: you can continue from a checkpoint once it is done.',
      compact: '⏳ A scene is being written: you can compact the story once it is done.',
      deleteSeed: '⏳ A scene is being written: you can delete the seed once it is done.',
      deleteBranch: '⏳ A scene is being written: you can delete the branch once it is done.',
    },
    compact: {
      startOrDeleteSeed: '⏳ Memory is being compacted: you can start a story or delete the seed once it is done.',
      switchOrDeleteBranch: '⏳ Memory is being compacted: you can switch or delete branches once it is done.',
      fork: '⏳ Memory is being compacted: you can continue from a checkpoint once it is done.',
      compact: '⏳ Memory is being compacted: you can compact again once it is done.',
      deleteSeed: '⏳ Memory is being compacted: you can delete the seed once it is done.',
      deleteBranch: '⏳ Memory is being compacted: you can delete the branch once it is done.',
    },
  },

  home: {
    title: '🏠 Menu',
    unknownRoute: '⚠️ That screen is no longer available. Here is the menu.',
    gpu: status => `🖥 GPU: ${status}`,
    sceneJob: story => `⏳ Writing a scene${story ? ` in ${story}` : ''}.`,
    compactJob: story => `⏳ Compacting memory${story ? ` in ${story}` : ''}.`,
    sceneJobNote: 'You can browse the menu. Deleting, switching branches and starting new scenes have to wait until it is done.',
    compactJobNote: 'You can browse the menu. Deleting, switching branches and starting new scenes have to wait until it is done.',
    current: story => `📖 Now playing: ${story}`,
    branch: (name, progress) => `🌿 Branch ${name} · ${progress}`,
    howToContinue: 'To continue, just send a message: a line of dialogue, what your character does, or a direction from the author. “Continue” writes the next scene without any direction.',
    noStory: 'No story selected.',
    noStoryHint: 'Open a seed to start a new story or return to one you have begun.',
    empty: 'Nothing here yet.',
    createFirst: 'Create your first seed: send its description in one or several messages, then save.',
  },

  language: {
    title: '🌐 Interface language',
    note: 'This changes only the menus and messages of the bot. The language of a story comes from its seed and from what you write.',
  },

  pictureStyle: {
    title: '🎨 Picture style',
    current: name => `Now: ${name}`,
    note: 'Tap a style to see its prompt, choose it or ask for a sample. A style changes only the pictures still to come; the ones already drawn stay as they are. Characters keep their looks: hair, clothes, features.',
    off: 'Pictures for your scenes are not switched on yet. Your choice is kept and applies once they are.',
    standard: '⚙️ Standard',
    presets: {
      semi: '🖌 Semi-realism',
      novel: '📖 Visual novel',
      film: '🎬 Film still',
      graphic: '🖋 Graphic novel',
      watercolor: '💧 Watercolor',
    },
    own: name => `✍️ ${name}`,
    add: '➕ New style',
    chosen: '✅ Your pictures are drawn in this style.',
    prompt: 'The style’s prompt (tap to copy):',
    tailNote: 'The bot adds the ending of the prompt to your text itself: people stay adults, and the picture has no lettering.',
    choose: '✅ Draw in this style',
    sample: '🖼 Sample on the last scene',
    edit: '✏️ Edit',
    remove: '🗑 Delete',
    back: '↩️ Back to styles',
    removeTitle: quotedName => `🗑 Delete the style ${quotedName}?`,
    removeChosen: name => `Your pictures are drawn in it now. Once it is deleted, they will be drawn in ${name}.`,
    removeYes: '🗑 Yes, delete',
    removeNo: '↩️ Keep it',
    newTitle: '➕ New picture style',
    editTitle: quotedName => `✏️ Style ${quotedName}`,
    inputNote: (max, nameMax) => `Send one message saying how to draw: technique, colors, light, mood, up to ${max} characters. You may put a name on the first line, up to ${nameMax} characters. Leave out the plot and the characters: they come from the scene. The picture model understands English best.`,
    editNote: max => `Send the new text in one message, up to ${max} characters. You may put a new name on the first line; otherwise the old one stays.`,
    example: 'For example:',
    exampleText: 'Oil by candlelight\nOil painting with visible impasto brushstrokes, warm candlelight and deep shadows.',
    copyHint: 'You can copy the prompt of any style from its card and change it.',
    nowText: 'Now:',
    backToStyle: '↩️ Back to the style',
    sampleCaption: name => `Style sample: ${name}`,
    drawingSample: '🎨 Drawing a sample…',
  },

  model: {
    title: '🤖 Model',
    noData: 'No model information yet.',
    providers: {
      'claude-code': { short: 'Claude Code', full: 'Claude Code on a Claude subscription (not our GPU server)' },
      'llama-cpp': { short: 'our server', full: 'our model server (llama.cpp)' },
      'codex-cli': { short: 'Codex', full: 'Codex CLI on a ChatGPT subscription (not our GPU server)' },
      'openai-compatible': { short: 'hosted API', full: 'a hosted OpenAI-style API (not our GPU server)' },
    },
    provider: full => `Provider: ${full}`,
    name: model => `Model: ${model}`,
    notes: {
      'claude-code': 'The model runs on a Claude subscription, not on our rented GPU.',
      'llama-cpp': 'This is our own model server. Its check does not measure the graphics card, GPU memory, speed or writing quality.',
      'codex-cli': 'The model runs on a ChatGPT subscription, not on our rented GPU. Story text is sent to a third-party service.',
      'openai-compatible': 'The model runs at a third-party provider, not on our rented GPU. Story text is sent to a third-party service.',
    },
    ready: time => `✅ Last successful check or reply: ${time ?? 'time unknown'}.`,
    readyNote: 'That was true at that moment; the bot does not watch the model all the time, so it may have stopped answering since.',
    unavailable: time => `⛔ Unavailable when checked: ${time ?? 'time unknown'}.`,
    unavailableNote: 'Until that changes, new scenes may fail.',
    configured: '⚪ Configured but not checked yet, so it is unknown whether it is ready.',
    unknown: '❔ Status unknown.',
    footer: 'The model is chosen in the bot settings, not in the chat.',
    short: {
      ready: time => (time ? `replied ${time}` : 'replied'),
      unavailable: 'unavailable when checked',
      configured: 'not checked',
      unknown: 'status unknown',
    },
  },

  gpu: {
    title: '🖥 GPU, shared by everyone who uses the bot',
    ready: n => `🟢 Running. Model jobs right now: ${jobs(n)}.`,
    autoPause: minutes => `It pauses by itself after ${minutes} min without model jobs, counted from the end of the last scene or compaction. Browsing the menu does not reset the timer.`,
    untilPause: minutes => `Auto-pause in ≈${minutes} min.`,
    untilPauseSoon: 'Auto-pause in less than a minute.',
    draining: n => `⏳ Pausing: waiting for every model job to finish (now: ${jobs(n)}).`,
    drainingNote: 'No new scenes or compactions start before the pause.',
    stopping: '⏳ Stopping. New scenes and compactions cannot start for now.',
    paused: '⏸ Paused: Vast confirmed the stop.',
    pausedNote: 'GPU time is no longer billed there, but the disk still is.',
    starting: '⏳ Starting. This can take a while: waiting for a free graphics card at Vast and for the model to warm up.',
    error: '⚠️ GPU control failed. That does not mean it is paused: it may be running and billed. Press “Refresh”.',
    unknown: '❔ GPU state unknown. That does not mean it is paused or free of charge. Press “Refresh”.',
    pauseHint: '“Pause GPU” stops it for everyone. If the model is working, the pause waits for every scene and compaction to finish.',
    startHint: '“Start GPU” can take a while too: a free graphics card and the model warming up.',
    storageNote: 'Stories and checkpoints are kept by the bot and survive a pause.',
    start: '▶️ Start GPU',
    pause: '⏸ Pause GPU',
    short: {
      ready: n => `running · jobs: ${jobs(n)}`,
      draining: n => `pausing, waiting for jobs: ${jobs(n)}`,
      stopping: 'stopping',
      paused: 'paused',
      starting: 'starting',
      error: 'error, open “Model” and refresh',
      unknown: 'state unknown, open “Model” and refresh',
    },
  },

  seeds: {
    title: '📚 Seeds',
    titleCount: n => `📚 Seeds: ${n}`,
    none: 'No seeds yet.',
    noStories: 'no stories',
    hint: 'Pick a seed to start a story or open one you have begun.',
  },

  seed: {
    notFound: 'Seed not found.',
    title: name => `🌱 Seed ${name}`,
    start: time => `World time at the start: ${time}`,
    startStory: '▶️ Start a new story',
    stories: n => `📖 Stories from this seed: ${n}`,
    story: n => `Story ${n}`,
    storyButton: n => `📖 Story ${n}`,
    noStories: 'No stories yet. “Start a new story” creates one and writes its first scene right away.',
    delete: '🗑 Delete seed',
    all: '📚 All seeds',
  },

  story: {
    notFound: 'Story not found.',
    branches: n => `🌿 Branches: ${n}`,
    none: 'No branches.',
    hint: 'A branch is a separate line of events. A new one appears when you continue the story from a checkpoint; the old one stays as it was.',
    tree: '🌳 Story tree',
    toSeed: '🌱 To the seed',
  },

  tree: {
    root: '🌱 start',
    run: (n, until) => `${count(n, 'scene', 'scenes')}${until ? ` until ${until}` : ''}`,
    more: n => `… and ${n} more`,
    compaction: '🗜 memory compaction',
    branch: 'branch',
    checkpoint: 'checkpoint',
    legend: '🌿 branch · 🗜 memory compaction · 📍 your checkpoint · ✅ you are here. A stretch with no forks or marks is folded into one line; times are world times. Every scene of a stretch is in the branch log below.',
    scenes: branch => `📜 Scenes: ${branch}`,
    toStory: '📖 To the story',
  },

  log: {
    title: name => `📜 Scenes of branch ${name}`,
    summary: n => `${count(n, 'scene', 'scenes')}, newest first`,
    compaction: '🗜 compaction',
    truncated: '⚠️ cut off',
    scene: 'scene',
    none: 'No scenes yet.',
    hint: 'Open a scene to read it or to continue from it in a new branch.',
    newer: '⬆️ Newer',
    older: 'Older ⬇️',
    tree: '🌳 Tree',
    toBranch: '🌿 To the branch',
  },

  branch: {
    notFound: 'Branch not found.',
    title: name => `🌿 Branch ${name}`,
    isCurrent: '✅ This is the current branch.',
    lastScene: 'Last scene:',
    pickHint: 'Choose this branch to play in it, and I will show its last scene.',
    play: '✅ Play in this branch',
    scenes: '📜 Scenes of the branch',
    checkpoints: n => `🔖 Checkpoints (${n})`,
    delete: '🗑 Delete branch',
    all: '◀️ All branches',
  },

  checkpoints: {
    title: (name, n) => `🔖 Checkpoints of branch ${name}: ${n}`,
    hint: 'Open a checkpoint to reread the scene and, if you like, continue from it in a new branch. Newest first.',
    none: 'No checkpoints yet. One appears after every scene.',
    newer: '⬅️ Newer',
    older: 'Older ➡️',
    toBranch: '◀️ To the branch',
  },

  checkpoint: {
    notFound: 'Checkpoint not found.',
    untitled: 'Checkpoint',
    branch: (name, story) => `🌿 Branch ${name} · ${story}`,
    isHead: '✅ This is the last scene of the current branch.',
    atStart: '🌱 The start of the story, no scenes yet.',
    start: time => `World time at the start: ${time}`,
    seedMissing: 'The seed is not available.',
    textMissing: 'The scene text is not available.',
    input: text => `✍️ Input: ${text}`,
    truncated: '⚠️ This scene was cut off during generation.',
    forkNote: name => `“Continue from here” starts a new branch at this point. Branch ${name} stays as it is.`,
    fork: '🌿 Continue from here',
    back: '◀️ Checkpoints',
  },

  context: {
    title: '📏 Context',
    titleOf: label => `📏 Context: ${label}`,
    checkpoint: 'checkpoint',
    branch: 'current branch',
    none: '📏 Context: no data yet.',
    noStory: 'No story selected. Open a seed and pick a branch.',
    currentBranch: '📏 Context of the current branch',
    noData: 'No context size data yet.',
    noCheckpointData: 'No size data for this checkpoint yet.',
    atCheckpoint: 'Size as of this checkpoint.',
    atBranch: 'Current branch, last saved state.',
    duringCompaction: '⏳ Memory is being compacted; this is the state before it.',
    duringScene: '⏳ The scene being written is not counted here.',
    window: (limit, reserve) => `Window: ${limit} tokens including the reply${reserve ? `; ${reserve} reserved for the reply` : ''}.`,
    windowUnknown: 'Window: size unknown.',
    nextRequest: (tokens, share) => `Next request ≈${tokens} tokens${share ? ` (≈${share} of the window)` : ''}: the snapshot, the bot's rules and a plain “Continue”. A long input adds its own size.`,
    nextRequestUnknown: 'Next request: no estimate.',
    estimateFromUsage: 'The estimate is checked against the last measured request of this line.',
    estimateFromBytes: 'Rough estimate: UTF-8 bytes ÷ 4 plus an allowance for overhead.',
    budget: (input, limit) => `Input budget (window minus reserve): ${input ? `≈${input}` : 'unknown'} of ${limit} tokens.`,
    remaining: tokens => `≈${tokens} tokens left.`,
    exhausted: '⚠️ By this estimate the input budget is already used up.',
    forecastNote: 'This is a forecast, not an exact count: the actual input is checked again when the model starts to answer, before any text is shown.',
    autoCompaction: (threshold, keep) => `Auto-compaction: when the input reaches ≈${threshold} tokens${keep === null ? '' : `; the latest ${count(keep, 'scene stays', 'scenes stay')} verbatim`}.`,
    autoCompactionNote: 'Measured tokens may correct the preliminary estimate. Checkpoints are saved before and after a compaction, and the original scenes stay in the archive.',
    snapshot: 'Snapshot (B is exact; ≈ is UTF-8 bytes ÷ 4, not an exact token count):',
    bytes: n => `${n} B`,
    bytesUnknown: 'size unknown',
    tokens: n => `≈${n} tokens`,
    tokensUnknown: 'tokens unknown',
    seed: size => `• Seed: ${size}`,
    memory: size => `• Memory: ${size}`,
    memoryEmpty: 'empty, no compactions yet',
    prefix: size => `= Seed + memory: ${size}`,
    tail: (scenes, size) => `• Uncompacted scenes${scenes === null ? '' : ` (${scenes})`}: ${size}`,
    whole: size => `= Whole snapshot: ${size}`,
    lastRequest: (input, output, total) => `Last request (measured): input ${input} · output ${output} · total ${total}`,
    lastRequestNone: 'Last request (measured): no measurements',
    lastRequestNote: 'Input includes the cache; output may include hidden model reasoning. This is one request, not the total spent so far and not a forecast of the next one.',
    compactNote: keep => `🗜 “Compact now” retells the old scenes into memory without waiting for the threshold. ${keep === null ? 'The latest scenes' : `The latest ${count(keep, 'scene', 'scenes')}`} stay verbatim, the original scenes are kept in the archive, and checkpoints are saved before and after. Compaction does not write a new scene.`,
  },

  scenePrefix: {
    context: (percent, rough) => `📏 Context ≈ ${percent}%${rough ? ', rough estimate' : ''}`,
    contextBelowOne: rough => `📏 Context under 1%${rough ? ', rough estimate' : ''}`,
  },

  deletion: {
    note: 'This removes it from the library the bot keeps, and it cannot be restored. Messages already sent to this chat stay.',
    seedTitle: name => `🗑 Delete seed ${name}?`,
    withSeed: 'Deleted with it, for good:',
    scenesAndCheckpoints: n => `${count(n, 'scene', 'scenes')} and all checkpoints`,
    includesCurrent: 'including the current story',
    onlySeed: 'There are no stories from this seed, so only the seed itself is deleted.',
    confirmAll: '🗑 Yes, delete everything',
    confirmSeed: '🗑 Yes, delete the seed',
    branchTitle: name => `🗑 Delete branch ${name}?`,
    onlyBranch: 'This is the only branch, so the whole story is deleted:',
    seedStays: name => `Seed ${name} stays, and you can start a new story from it.`,
    forever: 'Deleted for good:',
    checkpointsOfBranch: n => `${count(n, 'checkpoint', 'checkpoints')} of this branch`,
    scenesOnlyHere: n => `${count(n, 'scene', 'scenes')} found in no other branch`,
    scenesStay: 'no scenes: all of them are in other branches too',
    kept: n => `Kept: ${count(n, 'other branch', 'other branches')} of this story.`,
    isCurrent: '⚠️ This is the current branch. Pick another one after deleting it.',
    confirmBranch: '🗑 Yes, delete the branch',
    confirmStory: '🗑 Yes, delete the story',
  },

  newSeed: {
    title: '➕ New seed',
    steps: [
      'Send the description in one or several messages:',
      '1) first line: a title, up to 100 characters;',
      '2) second line: the date and time the story starts in its world, YYYY-MM-DD HH:MM;',
      '3) after that: the world, the character and the opening situation.',
      '',
      'A long text can be split across messages: everything goes into one draft.',
      '📎 Or attach a .txt / .md file (UTF-8, up to 256 KiB for the whole draft): either complete, with the title and date in its first lines, or the description alone, with the title and date sent as a message before the file. The file caption is ignored; PDF and DOCX will not work.',
      'When everything is sent, press “💾 Save seed”. Until then the seed is not saved and no scenes are written.',
    ].join('\n'),
    exampleLabel: 'Example:',
    example: [
      'The Lighthouse at the Edge of the World',
      '2026-08-02 20:00',
      'A northern island, late summer. Mira, 27, is spending her first evening as the lighthouse keeper. An empty boat with a lit lantern drifts up to the pier.',
    ].join('\n'),
    compactRunning: '⏳ The memory compaction started earlier is still running.',
    sceneRunning: '⏳ The scene started earlier is still being written.',
    cancel: '✖️ Cancel',
  },

  draft: {
    title: '📝 Seed draft, not saved yet',
    received: (parts, characters) => `Received: ${count(parts, 'part', 'parts')} · ${count(characters, 'character', 'characters')}`,
    more: 'You can send more messages or .txt / .md files, and they will be added to the description.',
    saveHint: 'When everything is sent, press “💾 Save seed”. No scenes are written now or on saving; you start a story separately.',
    menuNote: 'The menu and the other buttons work again once the draft is saved or discarded.',
    save: '💾 Save seed',
    discard: '🗑 Discard draft',
  },

  wait: {
    ahead: n => `Ahead of you in the model queue: ${count(n, 'request', 'requests')}.`,
    queued: n => `⏳ Model queue: ${count(n, 'request', 'requests')} ahead of you.`,
    next: '⏳ Your turn has come.',
    reading: '📖 The model is reading the story and will start writing soon…',
  },
  compact: {
    title: '🗜 Memory compaction',
    titleAutomatic: '🗜 Memory compaction before the new scene',
    now: {
      queued: '⏳ Now: waiting in the queue',
      extracting: '⏳ Now: the model is extracting memory from the scenes',
      validating: '⏳ Now: checking the memory structure and its references to scenes',
      saving: '⏳ Now: saving the memory and a checkpoint',
    },
    steps: { queued: 'queue', extracting: 'extraction', validating: 'check', saving: 'saving' },
    elapsed: time => `Elapsed: ${time}`,
    scope: (scenes, kept) => `Scenes in this compaction: ${scenes}; ${lastScenes(kept)} are left untouched.`,
    repair: scenes => `↩️ Extra extraction for missed scenes: ${scenes}.`,
    memoryJson: characters => `Memory JSON: ${count(characters, 'character', 'characters', grouped(characters))}`,
    extraJson: characters => `Extra JSON: ${count(characters, 'character', 'characters', grouped(characters))}`,
    live: 'This message updates as the work goes on.',
    cancelAutomatic: '✖️ Cancel',
    done: time => `✅ Compaction done${time ? ` · ${time}` : ''}`,
    summary: (scenes, facts) => `Scenes retold: ${scenes}, facts in memory: ${facts}.`,
    summaryScenes: scenes => `Scenes retold: ${scenes}.`,
    summaryFacts: facts => `Facts in memory: ${facts}.`,
    repaired: scenes => `Missed scenes (${scenes}) were added, and the reference check passed.`,
    kept: kept => `${kept === null ? 'The latest scenes' : `The latest ${count(kept, 'scene', 'scenes')}`} stayed as they were. The original scenes are kept, and there are checkpoints before and after the compaction.`,
    continues: 'The story goes on: the new scene is being written next.',
    failed: time => `⚠️ Compaction failed${time ? ` · ${time}` : ''}`,
    cancelled: time => `✖️ Compaction cancelled${time ? ` · ${time}` : ''}`,
    reason: reason => `Reason: ${reason}.`,
    reasons: {
      output_limit: 'the retelling did not fit into the model’s reply limit',
      finish_reason: 'the model cut its reply short',
      json: 'the model replied in the wrong format',
      shape: 'the model’s reply failed the structure check',
      fact: 'one of the facts failed its check',
      source: 'a fact referred to a scene outside this compaction',
      coverage: 'the retelling did not cover every scene',
      evidence: 'the references to evidence failed their check',
      quote: 'a quote was not found in its source scene',
      conflict: 'a detected contradiction was not recorded the required way',
      memory_not_smaller: 'the memory came out no shorter than the original scenes',
      provider_failed: 'the model is unavailable or returned an error',
      timeout: 'the model did not answer in time',
      context_limit: 'the scenes did not fit into the model’s context',
    },
    safe: 'The memory from this attempt was not saved. The original scenes and checkpoints are intact.',
    retry: command => `Try again: ${command}`,
    unknown: 'The compaction state is unknown. Check “Context”.',
    failure: 'Could not show the status. Check “Context”.',
  },

  notices: {
    unknownCommand: 'I do not know that command. Open /menu.',
    cancelled: 'Cancelled. Finished scenes and checkpoints are saved.',
    nothingToCompact: keep => `Nothing to compact yet: the latest ${count(keep, 'scene is', 'scenes are')} always kept verbatim. No new scene is written.`,
    nothingToCompactYet: keep => `Nothing to compact yet: the latest ${count(keep, 'scene is', 'scenes are')} always kept verbatim.`,
    textOnly: 'Only text messages are supported for now. Open /menu or write what your character does.',
    truncated: 'The reply hit the output token limit and may be cut off. The text received is saved. /continue carries the story on.',
    deliveryUnconfirmed: 'The scene is saved, but its delivery was not confirmed. /last shows it without generating again.',
    contextLimit: 'The seed, the accumulated memory, the latest scenes or the new input do not fit under the chosen context threshold. All original scenes and checkpoints are saved. You can shorten the input or open another point through /checkpoints.',
    compactionUnverified: command => `The compaction could not be verified. The original scenes and finished checkpoints are saved. Try again: ${command}.`,
    failed: command => `Could not finish the operation. Finished scenes and checkpoints are saved. Try again: ${command}.`,
    gpuNotConfigured: 'GPU rental control is not set up yet. /model shows the current model.',
    gpuPaused: 'The GPU has gone on pause. Open /model and start it, then send your action again.',
    drawing: '🎨 Drawing the illustration…',
    pictureFailed: 'The illustration did not work out. The scene is saved.',
    sampleFailed: 'The sample did not work out. Try again a little later.',
  },

  errors: {
    seedFormat: 'A seed needs a title (up to 100 characters), a date like 2026-08-02 20:00 and a description of the world, each starting on a new line.',
    seedGone: 'That seed has already been deleted.',
    pickBranch: 'Pick a story branch through /seeds.',
    pickStory: 'Pick a story or a checkpoint through /seeds.',
    checkpointGone: 'That checkpoint has already been deleted.',
    branchGone: 'That branch has already been deleted.',
    branchGoneOpenSeeds: 'That branch has already been deleted. Open /seeds.',
    jobRunning: 'A continuation is already on its way. /cancel stops it if the request is stuck.',
    sceneTime: 'The model did not give a valid date and time. The reply was not saved; send your continuation again.',
    busy: 'A scene or a compaction is already running. Wait for the reply or press /cancel, then send your message again.',
    busyNewSeed: 'A scene is already being written. Wait for the reply or press /cancel, then create the seed.',
    staleButton: 'That button is out of date. Open /menu.',
    staleConfirmation: 'That confirmation is out of date. Open the deletion again through /seeds.',
    gpuNotReady: 'The GPU is not ready right now. Open /model to start it or check its state, then send your action again.',
    unsupportedContent: 'The message contains something I cannot read. Send the seed or the continuation as text without attachments. Nothing was saved.',
    draftChanged: 'The draft changed while the file was loading. The file was not added; open /new and send it again.',
    otherDraft: 'That button belongs to another draft. Use “Save seed” under the last accepted part.',
    draftNeedsText: 'Send the next part of the seed as text. When you are done, press “Save seed”. /cancel discards the draft.',
    draftTooLarge: 'This part goes over the limit for a whole draft, 256 KiB of text. It was not added; the earlier parts stay in the draft. /cancel discards the draft.',
    draftClosed: 'That draft has already been saved or discarded. Create a new seed through /new.',
    fileNeedsDraft: 'To load a seed from a file, open /new first. The file was not added to the story.',
    fileFailed: 'Could not read the file. The draft is unchanged; send the file again.',
    fileIncomplete: 'Could not read the whole file. The draft is unchanged; send the file again.',
    fileTooLarge: 'The file is too large. The limit for a file and for the whole draft is 256 KiB of text.',
    fileType: 'Send a .txt or .md text file in UTF-8. PDF and DOCX are not supported yet.',
    fileEncoding: 'Could not read the file as UTF-8. Save it as UTF-8 and send it again; the draft is unchanged.',
    fileBinary: 'The file must be a non-empty .txt or .md text file with no binary data. The draft is unchanged.',
    styleNeedsText: 'Send the style as text, in one message. To leave without a change, tap “↩️” or send /cancel.',
    styleTooLong: 'Too long: a style has to fit in 400 characters. Shorten it and send it again.',
    stylesFull: 'Your library already has 10 styles of your own. To add a new one, delete one of them.',
    sampleOff: 'Pictures for your scenes are not switched on, so a sample cannot be drawn.',
    sampleBusy: 'The scene is still being written. Ask for a sample once it arrives.',
    sampleNoScene: 'A sample is drawn from your last scene. Start a story, and after its first scene you can ask for one.',
    sampleInFlight: 'Already drawing a sample. You can ask for the next one once it arrives.',
  },

  labels: {
    firstBranch: 'Start',
    seedCheckpoint: 'Seed',
    forkBranch: from => `From ${from}`,
    forkCheckpoint: 'Fork point',
    scene: n => `Scene ${n}`,
    beforeCompaction: 'Before compaction',
    afterCompaction: 'After compaction',
  },

  commands: {
    menu: 'Story menu',
    seeds: 'My seeds',
    new: 'Create a seed',
    checkpoints: 'Scenes and checkpoints',
    continue: 'Continue the story',
    last: 'Show the last scene',
    context: 'Context size and token counts',
    compact: 'Compact early scenes into memory now',
    model: 'Current model and connection',
    language: 'Interface language',
    style: 'Picture style for the scenes',
    gpu_pause: 'Pause the GPU once work is finished',
    gpu_start: 'Start the rented GPU',
    cancel: 'Cancel input or generation',
  },
};
