// Japanese interface catalog. Keys, arguments and the notes for translators are in ru.ts, which defines `Messages`.
//
// Glossary, one term per concept:
// - seed: シード (as in a world seed of a game; 種 reads ambiguously), story: 物語, scene: シーン
// - branch: ルート (what Japanese story games call a line of events), fork point: 分岐点, story tree: 物語ツリー
// - checkpoint: チェックポイント, continue from here: ここから続ける, current: 現在の…, being played: プレイ中
// - memory: 記憶 (メモリ is left for GPU memory), compaction: 圧縮, retell: 要約, the latest N scenes: 直近のNシーン
// - context: コンテキスト, window: ウィンドウ, snapshot: スナップショット, model: モデル, model job: ジョブ
// - draft: 下書き, part: パート, world time: 作中の日時, measured: 実測, estimate: 見積もり, rough estimate: 概算
// - a running job is stopped with 中止, an input with キャンセル, a draft with 破棄; GPU pause: 一時停止
// A /command keeps an ASCII space after it, or Telegram does not make it a link before kana or kanji.

import type { Messages } from './ru.ts';

const grouped = (n: number) => String(Math.round(n)).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
const lastScenes = (n: number | null) => (n === null ? '直近のシーン' : `直近の${n}シーン`);
const jobs = (n: number | null) => (n === null ? '不明' : String(n));
const textSize = (label: string, tokens: number | null, chars: number) =>
  `${label}：${tokens === null ? 'トークン数は不明' : `${grouped(tokens)} トークン`} · ${grouped(chars)} 文字`;

export const ja: Messages = {
  format: {
    number: n => grouped(n),
    quote: text => `「${text}」`,
    untitled: '無題',
    untitledButton: '無題',
    unknown: '不明',
  },

  count: {
    scenes: n => `${n}シーン`,
    stories: n => `物語${n}本`,
    branches: n => `${n}ルート`,
    checkpoints: n => `チェックポイント${n}件`,
    parts: n => `${n}パート`,
    characters: n => `${n}文字`,
  },

  duration: {
    seconds: s => `${s}秒`,
    minutes: (m, ss) => `${m}分${ss}秒`,
    hours: (h, mm) => `${h}時間${mm}分`,
  },

  buttons: {
    menu: '🏠 メニュー',
    continue: '▶️ 続ける',
    stop: '✖️ 停止',
    lastScene: '📄 最後のシーン',
    context: '📏 コンテキスト',
    model: '🤖 モデル',
    checkpoints: '🔖 チェックポイント',
    branches: '🌿 ルート',
    seeds: '📚 シード',
    seedsCount: n => `📚 シード（${n}）`,
    newSeed: '➕ 新しいシード',
    refresh: '🔄 更新',
    compactNow: '🗜 今すぐ圧縮',
    cancelScene: '✖️ 生成を中止',
    cancelCompaction: '✖️ 圧縮を中止',
    toCheckpoint: '◀️ チェックポイントへ',
    previous: '⬅️ 前へ',
    next: '次へ ➡️',
    keep: '↩️ 削除しない',
    pictureStyle: '🎨 挿絵のスタイル',
    characters: '👤 登場人物',
  },

  common: {
    current: '✅ プレイ中',
    page: (page, pages) => `${page} / ${pages} ページ`,
    storyName: (title, n) => `${title} · 物語 ${n}`,
    noScenes: 'まだシーンなし',
    staleHint: 'すでに削除されたか、画面が古くなっている可能性があります。',
    failure: '⚠️ この画面を表示できませんでした。',
    failureHint: 'メニューに戻って、もう一度試してください。',
    whatIsSeed: 'シードとは、世界・登場人物・最初の状況をまとめた設定です。1つのシードから、物語をいくつでも始められます。',
  },

  busy: {
    scene: {
      startOrDeleteSeed: '⏳ シーンを執筆中です。物語の開始やシードの削除は、書き終わってからできます。',
      switchOrDeleteBranch: '⏳ シーンを執筆中です。ルートの切り替えや削除は、書き終わってからできます。',
      fork: '⏳ シーンを執筆中です。チェックポイントから続けるのは、書き終わってからできます。',
      compact: '⏳ シーンを執筆中です。物語の圧縮は、書き終わってからできます。',
      deleteSeed: '⏳ シーンを執筆中です。シードの削除は、書き終わってからできます。',
      deleteBranch: '⏳ シーンを執筆中です。ルートの削除は、書き終わってからできます。',
    },
    compact: {
      startOrDeleteSeed: '⏳ 記憶を圧縮中です。物語の開始やシードの削除は、圧縮が終わってからできます。',
      switchOrDeleteBranch: '⏳ 記憶を圧縮中です。ルートの切り替えや削除は、圧縮が終わってからできます。',
      fork: '⏳ 記憶を圧縮中です。チェックポイントから続けるのは、圧縮が終わってからできます。',
      compact: '⏳ 記憶を圧縮中です。物語の圧縮は、今の圧縮が終わってからできます。',
      deleteSeed: '⏳ 記憶を圧縮中です。シードの削除は、圧縮が終わってからできます。',
      deleteBranch: '⏳ 記憶を圧縮中です。ルートの削除は、圧縮が終わってからできます。',
    },
  },

  home: {
    title: '🏠 メニュー',
    unknownRoute: '⚠️ この画面はもう利用できません。メニューを表示します。',
    gpu: status => `🖥 GPU：${status}`,
    sceneJob: story => `⏳ ${story ? `${story} の` : ''}シーンを執筆中です。`,
    compactJob: story => `⏳ ${story ? `${story} の` : ''}記憶を圧縮中です。`,
    sceneJobNote: 'メニューは見られます。削除、ルートの切り替え、新しいシーンの開始は、書き終わってからできます。',
    compactJobNote: 'メニューは見られます。削除、ルートの切り替え、新しいシーンの開始は、圧縮が終わってからできます。',
    current: story => `📖 プレイ中：${story}`,
    branch: (name, progress) => `🌿 ルート${name} · ${progress}`,
    howToContinue: '続けるには、メッセージを送るだけです。セリフ、主人公の行動、作者としての指示のどれでもかまいません。「続ける」を押すと、指示なしで次のシーンに進みます。',
    noStory: '物語が選択されていません。',
    noStoryHint: 'シードを開いて、新しい物語を始めるか、途中の物語に戻ってください。',
    empty: 'まだ何もありません。',
    createFirst: '最初のシードを作りましょう。説明を1通または数通のメッセージで送って、保存してください。',
  },

  language: {
    title: '🌐 表示言語',
    note: '変わるのは、メニューとボットのメッセージの言語だけです。物語の言語は、シードと送るメッセージで決まります。',
  },

  pictureStyle: {
    title: '🎨 挿絵のスタイル',
    current: name => `現在：${name}`,
    note: 'スタイルをタップすると、プロンプトを見たり、そのスタイルを選んだり、サンプルを頼んだりできます。スタイルが変わるのはこれから描く挿絵だけで、描き終えた挿絵はそのままです。登場人物の外見（髪、服装、特徴）は変わりません。',
    off: 'あなたのシーンにはまだ挿絵が有効になっていません。選択は保存され、有効になると適用されます。',
    standard: '⚙️ 標準',
    presets: {
      semi: '🖌 セミリアル',
      novel: '📖 ビジュアルノベル',
      film: '🎬 映画のワンシーン',
      graphic: '🖋 グラフィックノベル',
      watercolor: '💧 水彩',
    },
    own: name => `✍️ ${name}`,
    add: '➕ 新しいスタイル',
    chosen: '✅ 挿絵はこのスタイルで描かれています。',
    prompt: 'スタイルのプロンプト（タップでコピー）：',
    choose: '✅ このスタイルで描く',
    sample: '🖼 最新のシーンでサンプル',
    sampleAll: '🖼 最新のシーンで全スタイル',
    edit: '✏️ 編集',
    remove: '🗑 削除',
    back: '↩️ スタイル一覧へ',
    removeTitle: quotedName => `🗑 スタイル${quotedName}を削除しますか？`,
    removeChosen: name => `いま挿絵はこのスタイルで描かれています。削除すると${name}で描かれます。`,
    removeYes: '🗑 はい、削除します',
    removeNo: '↩️ 残す',
    newTitle: '➕ 新しい挿絵スタイル',
    editTitle: quotedName => `✏️ スタイル${quotedName}`,
    inputNote: (max, nameMax) => `どう描くかを1通のメッセージで送ってください。技法、色、光、雰囲気など、${max}文字までです。1行目に名前を書けます（${nameMax}文字まで）。あらすじや登場人物は書かないでください。シーンから取ります。挿絵のモデルは英語を最もよく理解します。`,
    editNote: max => `新しい文を1通のメッセージで、${max}文字まで送ってください。1行目に新しい名前を書けます。書かなければ今の名前のままです。`,
    example: '例：',
    exampleText: 'ろうそくの油彩\nOil painting with visible impasto brushstrokes, warm candlelight and deep shadows.',
    copyHint: 'どのスタイルのプロンプトも、そのカードからコピーして書き換えられます。',
    nowText: '現在：',
    backToStyle: '↩️ スタイルに戻る',
    sampleCaption: name => `スタイルのサンプル：${name}`,
    drawingSample: '🎨 サンプルを描いています…',
    // `count` is how many styles are drawn, one picture each.
    drawingAll: (count: number) => `🎨 最新のシーンを全${count}スタイルで描いています。画像は1枚ずつ届きます。物語で次の行動をすると描画は止まります。`,
  },

  characters: {
    title: story => `👤 登場人物：${story}`,
    note: 'この物語の挿絵は登場人物をこう描きます。人物をタップすると、説明の全文を見たり、外見を編集したり、肖像を描いたりできます。',
    none: '登場人物は、物語の最初の挿絵のあとに表示されます。',
    toStory: '📖 物語へ',
    cardTitle: (person, story) => `👤 ${person} · ${story}`,
    look: '外見（タップでコピー）：',
    lookSize: (tokens, chars) => textSize('外見のテキスト', tokens, chars),
    clothesOfBranch: branch => `ルート${branch}の最新の挿絵での服装：`,
    clothesAtStart: 'この物語の挿絵が始まったときの服装：',
    clothesSize: (tokens, chars) => textSize('服装のテキスト', tokens, chars),
    noClothes: '服装はまだ記録されていません。',
    clothesNote: '服装はここでは編集しません。服装は物語の中で変わり、挿絵はシーンから服装を取ります。',
    sizeNote: '数値はテキストごとに別々に数えたものです。プロンプトの大きさではありません。挿絵を描くときにテキストは短くされ、ほかのテキストとつなげられます。正確な大きさは各挿絵の下にあります。',
    scope: '外見の変更は、この物語のすべてのルートでこれから描く挿絵に適用されます。物語の本文、記憶、描き終えた挿絵は変わりません。いま描いている挿絵は、前の外見で描かれることがあります。',
    portraitNone: '🖼 肖像はまだありません。肖像はこの外見から顔と全身の体つきを描くので、参考画像を選びやすくなります。',
    portraitKept: '🖼 肖像を保存しました。この外見で描いた顔と体つきです。',
    portraitStale: '🖼 保存した肖像は前の外見で描かれています。新しく描くと、今の外見での顔と体つきが見られます。',
    edit: '✏️ 外見を編集',
    portrait: '🖼 肖像',
    back: '↩️ 登場人物一覧へ',
    editTitle: (person, story) => `✏️ 外見：${person} · ${story}`,
    editNote: max => `新しい外見を1通のメッセージで、${max}文字まで送ってください。顔、髪、体つき、身長、特徴など。服装と名前は書かないでください。服装は物語が変え、名前はそのままです。挿絵のモデルは英語を最もよく理解します。`,
    nowText: '現在：',
    backToCard: '↩️ 人物に戻る',
    caption: person => `🖼 肖像：${person}。顔と全身の体つきを、飾り気のない中立的な服装で描いています。`,
    again: '🔄 別の案',
    keep: '✅ これを残す',
    kept: person => `✅ 肖像を保存しました：${person}。シーンの挿絵にはまだ使われません。`,
    drawing: '🎨 肖像を描いています…',
    portraitFailed: '肖像は描けませんでした。少し時間をおいてもう一度お試しください。',
  },

  model: {
    title: '🤖 モデル',
    noData: 'モデルの情報はまだありません。',
    providers: {
      'claude-code': { short: 'Claude Code', full: 'Claudeのサブスクリプションで動くClaude Code（自前のGPUサーバーではありません）' },
      'llama-cpp': { short: '自前サーバー', full: '自前のモデルサーバー（llama.cpp）' },
      'simple-serving': { short: '自前サーバー', full: '自前のモデルサーバー（vLLM）' },
      'codex-cli': { short: 'Codex', full: 'ChatGPTのサブスクリプションで動くCodex CLI（自前のGPUサーバーではありません）' },
      'openai-compatible': { short: '外部API', full: 'OpenAI互換の外部API（自前のGPUサーバーではありません）' },
    },
    provider: full => `プロバイダー：${full}`,
    name: model => `モデル：${model}`,
    notes: {
      'claude-code': 'モデルはClaudeのサブスクリプションで動いています。こちらで借りているGPUは使いません。',
      'llama-cpp': 'これは自前のモデルサーバーです。チェックでは、グラフィックカード、GPUメモリ、速度、文章の質は測りません。',
      'simple-serving': 'これは自前のモデルサーバーです。チェックでは、グラフィックカード、GPUメモリ、速度、文章の質は測りません。',
      'codex-cli': 'モデルはChatGPTのサブスクリプションで動いています。こちらで借りているGPUは使いません。物語のテキストは外部サービスに送信されます。',
      'openai-compatible': 'モデルは外部プロバイダーで動いています。こちらで借りているGPUは使いません。物語のテキストは外部サービスに送信されます。',
    },
    ready: time => `✅ 最後に成功したチェックまたは応答：${time ?? '時刻不明'}。`,
    readyNote: 'これはその時点の状態で、常に監視しているわけではありません。今は応答しなくなっている可能性もあります。',
    unavailable: time => `⛔ チェック時に利用不可：${time ?? '時刻不明'}。`,
    unavailableNote: 'この状態が続く間は、新しいシーンが失敗することがあります。',
    configured: '⚪ 設定済みですが、まだチェックしていません。使える状態かどうかは不明です。',
    unknown: '❔ 状態は不明です。',
    footer: 'モデルはチャットではなく、ボットの設定で選びます。',
    short: {
      ready: time => (time ? `${time} に応答` : '応答あり'),
      unavailable: 'チェック時に利用不可',
      configured: '未チェック',
      unknown: '状態不明',
    },
  },

  gpu: {
    title: '🖥 GPU（ボットの全ユーザーで共有）',
    ready: n => `🟢 稼働中です。実行中のジョブ：${jobs(n)}。`,
    autoPause: minutes => `ジョブのない状態が${minutes}分続くと、自動で一時停止します。最後のジョブが終わった時点から数えます。メニューを見ても、このカウントはリセットされません。`,
    untilPause: minutes => `自動一時停止まで約${minutes}分です。`,
    untilPauseSoon: '自動一時停止まで1分未満です。',
    draining: n => `⏳ 一時停止の準備中です。すべてのジョブが終わるのを待っています（現在：${jobs(n)}）。`,
    drainingNote: '一時停止するまで、新しいシーンと圧縮は始まりません。',
    stopping: '⏳ 停止処理中です。今は新しいシーンと圧縮を始められません。',
    paused: '⏸ 一時停止中です。Vastが停止を確認しました。',
    pausedNote: 'GPUの稼働料金はかからなくなりますが、ディスクの料金は引き続きかかります。',
    starting: '⏳ 起動中です。Vastで空きのグラフィックカードを待ち、モデルをウォームアップするため、時間がかかることがあります。',
    error: '⚠️ GPUの制御でエラーが起きました。一時停止中とは限らず、稼働して料金がかかっている可能性があります。「更新」を押してください。',
    unknown: '❔ GPUの状態は不明です。一時停止中とも、料金がかかっていないとも限りません。「更新」を押してください。',
    pauseHint: '「GPUを一時停止」は、全ユーザーのGPUを止めます。モデルが動いている場合は、すべてのシーンと圧縮が終わってから一時停止します。',
    startHint: '「GPUを起動」にも時間がかかることがあります。空きのグラフィックカードの確保と、モデルのウォームアップが必要です。',
    storageNote: '物語とチェックポイントはボット側に保存されていて、一時停止しても消えません。',
    start: '▶️ GPUを起動',
    pause: '⏸ GPUを一時停止',
    short: {
      ready: n => `稼働中 · ジョブ：${jobs(n)}`,
      draining: n => `一時停止の準備中、ジョブ待ち：${jobs(n)}`,
      stopping: '停止処理中',
      paused: '一時停止中',
      starting: '起動中',
      error: 'エラー。「モデル」を開いて更新してください',
      unknown: '状態不明。「モデル」を開いて更新してください',
    },
  },

  seeds: {
    title: '📚 シード',
    titleCount: n => `📚 シード：${n}`,
    none: 'シードはまだありません。',
    noStories: '物語なし',
    hint: 'シードを選ぶと、物語を始めたり、途中の物語を開いたりできます。',
  },

  seed: {
    notFound: 'シードが見つかりません。',
    title: name => `🌱 シード${name}`,
    start: time => `作中の開始日時：${time}`,
    startStory: '▶️ 新しい物語を始める',
    stories: n => `📖 このシードの物語：${n}`,
    story: n => `物語 ${n}`,
    storyButton: n => `📖 物語 ${n}`,
    noStories: '物語はまだありません。「新しい物語を始める」を押すと、物語を作成して、すぐに最初のシーンを書きます。',
    delete: '🗑 シードを削除',
    all: '📚 すべてのシード',
  },

  story: {
    notFound: '物語が見つかりません。',
    branches: n => `🌿 ルート：${n}`,
    none: 'ルートはありません。',
    hint: 'ルートとは、独立した出来事の流れです。チェックポイントから物語を続けると新しいルートができ、元のルートはそのまま残ります。',
    tree: '🌳 物語ツリー',
    toSeed: '🌱 シードへ',
  },

  tree: {
    root: '🌱 始まり',
    run: (n, until) => `${n}シーン${until ? ` ～${until}` : ''}`,
    more: n => `… ほか${n}件`,
    compaction: '🗜 記憶の圧縮',
    branch: 'ルート',
    checkpoint: 'チェックポイント',
    legend: '🌿 ルート · 🗜 記憶の圧縮 · 📍 自分のチェックポイント · ✅ 現在地。分岐も印もない区間は、1行にまとめています。時刻は作中のものです。区間内の各シーンは、下のルートのシーン一覧で見られます。',
    scenes: branch => `📜 シーン：${branch}`,
    toStory: '📖 物語へ',
  },

  log: {
    title: name => `📜 ルート${name}のシーン`,
    summary: n => `${n}シーン、新しい順`,
    compaction: '🗜 圧縮',
    truncated: '⚠️ 途切れ',
    scene: 'シーン',
    none: 'シーンはまだありません。',
    hint: 'シーンを開くと、読み返したり、そこから新しいルートで続けたりできます。',
    newer: '⬆️ 新しい方へ',
    older: '古い方へ ⬇️',
    tree: '🌳 ツリー',
    toBranch: '🌿 ルートへ',
  },

  branch: {
    notFound: 'ルートが見つかりません。',
    title: name => `🌿 ルート${name}`,
    isCurrent: '✅ 現在のルートです。',
    lastScene: '最後のシーン：',
    pickHint: 'このルートを選ぶと、ここでプレイできます。選んだら最後のシーンを表示します。',
    play: '✅ このルートでプレイ',
    scenes: '📜 ルートのシーン',
    checkpoints: n => `🔖 チェックポイント（${n}）`,
    delete: '🗑 ルートを削除',
    all: '◀️ すべてのルート',
  },

  checkpoints: {
    title: (name, n) => `🔖 ルート${name}のチェックポイント：${n}`,
    hint: 'チェックポイントを開くと、シーンを読み返せます。そこから新しいルートで続けることもできます。新しい順に並んでいます。',
    none: 'チェックポイントはまだありません。シーンごとに自動で作られます。',
    newer: '⬅️ 新しい方へ',
    older: '古い方へ ➡️',
    toBranch: '◀️ ルートへ',
  },

  checkpoint: {
    notFound: 'チェックポイントが見つかりません。',
    untitled: 'チェックポイント',
    branch: (name, story) => `🌿 ルート${name} · ${story}`,
    isHead: '✅ 現在のルートの最後のシーンです。',
    atStart: '🌱 物語の始まりです。シーンはまだありません。',
    start: time => `作中の開始日時：${time}`,
    seedMissing: 'シードを利用できません。',
    textMissing: 'シーンのテキストを利用できません。',
    input: text => `✍️ 入力：${text}`,
    truncated: '⚠️ このシーンは生成中に途切れました。',
    forkNote: name => `「ここから続ける」を押すと、この時点から新しいルートができます。ルート${name}はそのまま残ります。`,
    fork: '🌿 ここから続ける',
    back: '◀️ チェックポイント',
  },

  context: {
    title: '📏 コンテキスト',
    titleOf: label => `📏 コンテキスト：${label}`,
    checkpoint: 'チェックポイント',
    branch: '現在のルート',
    none: '📏 コンテキスト：データはまだありません。',
    noStory: '物語が選択されていません。シードを開いて、ルートを選んでください。',
    currentBranch: '📏 現在のルートのコンテキスト',
    noData: 'コンテキストサイズのデータはまだありません。',
    noCheckpointData: 'このチェックポイントのサイズのデータはまだありません。',
    atCheckpoint: 'このチェックポイント時点のサイズです。',
    atBranch: '現在のルートの、最後に保存された状態です。',
    duringCompaction: '⏳ 記憶を圧縮中です。ここに出ているのは圧縮前の状態です。',
    duringScene: '⏳ 執筆中のシーンは、ここには含まれていません。',
    window: (limit, reserve) => `ウィンドウ：応答を含めて${limit}トークン${reserve ? `、うち応答用の予約が${reserve}` : ''}。`,
    windowUnknown: 'ウィンドウ：サイズ不明。',
    nextRequest: (tokens, share) => `次のリクエスト：≈${tokens}トークン${share ? `（ウィンドウの≈${share}）` : ''}。内訳はスナップショット、ボットのルール、通常の「続ける」です。長い入力は、その分だけ増えます。`,
    nextRequestUnknown: '次のリクエスト：見積もりなし。',
    estimateFromUsage: '見積もりは、この系統で最後に実測したリクエストと照合しています。',
    estimateFromBytes: '概算：UTF-8バイト数 ÷ 4 に、システム部分の余裕を加えた値です。',
    budget: (input, limit) => `入力の予算（ウィンドウから予約を引いた分）：${input ? `≈${input}` : '不明'} / ${limit}トークン。`,
    remaining: tokens => `残り≈${tokens}トークン。`,
    exhausted: '⚠️ 見積もりでは、入力の予算をすでに使い切っています。',
    forecastNote: 'これは予測で、正確な計算ではありません。実際の入力量は、モデルが応答を始めるとき、テキストを表示する前にもう一度確認します。',
    autoCompaction: (threshold, keep) => `自動圧縮：入力が≈${threshold}トークンに達したとき${keep === null ? '' : `。直近の${keep}シーンはそのまま残ります`}。`,
    autoCompactionNote: '実測したトークン数によって、事前の見積もりが修正されることがあります。圧縮の前後にはチェックポイントが保存され、元のシーンはアーカイブに残ります。',
    snapshot: 'スナップショット（B は正確な値。≈ は UTF-8バイト数 ÷ 4 で、正確なトークン数ではありません）：',
    bytes: n => `${n} B`,
    bytesUnknown: 'サイズ不明',
    tokens: n => `≈${n}トークン`,
    tokensUnknown: 'トークン数不明',
    seed: size => `• シード：${size}`,
    memory: size => `• 記憶：${size}`,
    memoryEmpty: '空、まだ圧縮していません',
    prefix: size => `= シード + 記憶：${size}`,
    tail: (scenes, size) => `• 未圧縮のシーン${scenes === null ? '' : `（${scenes}）`}：${size}`,
    whole: size => `= スナップショット全体：${size}`,
    lastRequest: (input, output, total) => `最後のリクエスト（実測）：入力 ${input} · 出力 ${output} · 合計 ${total}`,
    lastRequestNone: '最後のリクエスト（実測）：データなし',
    lastRequestNote: '入力にはキャッシュ分も含まれます。出力には、モデルの表示されない推論が含まれることがあります。これは1回のリクエストの値で、これまでの累計でも、次回の予測でもありません。',
    compactNote: keep => `🗜 「今すぐ圧縮」を押すと、しきい値を待たずに、古いシーンを要約して記憶に移します。${lastScenes(keep)}はそのまま残り、元のシーンはアーカイブに保存され、圧縮の前後にチェックポイントが作られます。圧縮では新しいシーンは書かれません。`,
  },

  scenePrefix: {
    context: (percent, rough) => `📏 コンテキスト ≈ ${percent}%${rough ? '、概算' : ''}`,
    contextBelowOne: rough => `📏 コンテキスト 1%未満${rough ? '、概算' : ''}`,
  },

  deletion: {
    note: '削除すると元には戻せません。削除したシーンの挿絵は、送信から2日以内のものならボットがこのチャットから消します。チャット内のシーンのテキストは残ります。',
    seedTitle: name => `🗑 シード${name}を削除しますか？`,
    withSeed: '一緒に完全に削除されるもの：',
    scenesAndCheckpoints: n => `${n}シーンとすべてのチェックポイント`,
    includesCurrent: '現在の物語を含む',
    onlySeed: 'このシードの物語はないため、シードだけが削除されます。',
    confirmAll: '🗑 はい、すべて削除',
    confirmSeed: '🗑 はい、シードを削除',
    branchTitle: name => `🗑 ルート${name}を削除しますか？`,
    onlyBranch: 'これが唯一のルートのため、物語全体が削除されます：',
    seedStays: name => `シード${name}は残ります。そこから新しい物語を始められます。`,
    forever: '完全に削除されるもの：',
    checkpointsOfBranch: n => `このルートのチェックポイント${n}件`,
    scenesOnlyHere: n => `ほかのルートにない${n}シーン`,
    scenesStay: 'シーンは残ります（すべてほかのルートにもあります）',
    kept: n => `残るもの：この物語のほかの${n}ルート。`,
    isCurrent: '⚠️ これは現在のルートです。削除したら、別のルートを選んでください。',
    confirmBranch: '🗑 はい、ルートを削除',
    confirmStory: '🗑 はい、物語を削除',
  },

  newSeed: {
    title: '➕ 新しいシード',
    steps: [
      '説明を1通または数通のメッセージで送ってください：',
      '1) 1行目：タイトル（100文字まで）',
      '2) 2行目：作中の開始日時。形式は YYYY-MM-DD HH:MM',
      '3) 3行目以降：世界、登場人物、最初の状況',
      '',
      '長い文章は、複数のメッセージに分けてもかまいません。すべて1つの下書きにまとまります。',
      '📎 .txt / .md ファイル（UTF-8、下書き全体で256 KiBまで）を添付することもできます。最初の行にタイトルと日時を入れた完全な形でも、説明だけでもかまいません。説明だけの場合は、ファイルの前にタイトルと日時をメッセージで送ってください。ファイルのキャプションは無視されます。PDFとDOCXは使えません。',
      'すべて送ったら「💾 シードを保存」を押してください。それまでシードは保存されず、シーンも書かれません。',
    ].join('\n'),
    exampleLabel: '例：',
    example: [
      '世界の果ての灯台',
      '2026-08-02 20:00',
      '北の島、夏の終わり。27歳のミラは、灯台守として働く最初の夜を迎えている。桟橋に、灯りのともったランタンを載せた無人の小舟が流れ着く。',
    ].join('\n'),
    compactRunning: '⏳ 先に始まった記憶の圧縮が、まだ続いています。',
    sceneRunning: '⏳ 先に始まったシーンを、まだ執筆中です。',
    cancel: '✖️ キャンセル',
  },

  draft: {
    title: '📝 シードの下書き（未保存）',
    received: (parts, characters) => `受信済み：${parts}パート · ${characters}文字`,
    more: 'メッセージや .txt / .md ファイルをさらに送ると、説明に追加されます。',
    saveHint: 'すべて送ったら「💾 シードを保存」を押してください。今も保存時も、シーンは書かれません。物語は別に始められます。',
    menuNote: 'メニューやほかのボタンは、下書きを保存するか破棄すると、また使えるようになります。',
    save: '💾 シードを保存',
    discard: '🗑 下書きを破棄',
  },

  wait: {
    ahead: n => `モデルの待ち行列であなたの前に${n}件あります。`,
    queued: n => `⏳ モデルの順番待ち：前に${n}件。`,
    next: '⏳ あなたの番になりました。',
    reading: '📖 モデルが物語を読んでいます。まもなく書き始めます…',
  },
  compact: {
    title: '🗜 記憶の圧縮',
    titleAutomatic: '🗜 新しいシーンの前に記憶を圧縮',
    now: {
      queued: '⏳ 現在：順番待ち',
      extracting: '⏳ 現在：モデルがシーンから記憶を抽出中',
      validating: '⏳ 現在：記憶の構造とシーンへの参照を検証中',
      saving: '⏳ 現在：記憶とチェックポイントを保存中',
    },
    steps: { queued: '待機', extracting: '抽出', validating: '検証', saving: '保存' },
    elapsed: time => `経過：${time}`,
    scope: (scenes, kept) => `今回圧縮するシーン：${scenes}。${lastScenes(kept)}はそのまま残します。`,
    repair: scenes => `↩️ 漏れたシーンの追加抽出：${scenes}。`,
    memoryJson: characters => `記憶のJSON：${grouped(characters)}文字`,
    extraJson: characters => `追加のJSON：${grouped(characters)}文字`,
    live: 'このメッセージは、進行に合わせて更新されます。',
    cancelAutomatic: '✖️ 中止',
    done: time => `✅ 圧縮が完了しました${time ? ` · ${time}` : ''}`,
    summary: (scenes, facts) => `要約したシーン：${scenes}、記憶内の事実：${facts}。`,
    summaryScenes: scenes => `要約したシーン：${scenes}。`,
    summaryFacts: facts => `記憶内の事実：${facts}。`,
    repaired: scenes => `漏れていたシーン（${scenes}）を補い、参照の検証に合格しました。`,
    kept: kept => `${lastScenes(kept)}はそのまま残っています。元のシーンは保存されていて、圧縮の前後にチェックポイントがあります。`,
    continues: '物語は続きます。次に新しいシーンを書きます。',
    failed: time => `⚠️ 圧縮に失敗しました${time ? ` · ${time}` : ''}`,
    cancelled: time => `✖️ 圧縮を中止しました${time ? ` · ${time}` : ''}`,
    reason: reason => `理由：${reason}。`,
    reasons: {
      output_limit: '要約がモデルの応答上限に収まりませんでした',
      finish_reason: 'モデルが応答を途中で打ち切りました',
      json: 'モデルの応答が指定の形式ではありませんでした',
      shape: 'モデルの応答が構造の検証に合格しませんでした',
      fact: '事実の1つが検証に合格しませんでした',
      source: '事実が今回の圧縮に含まれないシーンを参照していました',
      coverage: '要約が一部のシーンを扱っていませんでした',
      evidence: '根拠への参照が検証に合格しませんでした',
      quote: '引用が元のシーンに見つかりませんでした',
      conflict: '検出された矛盾が所定の形式で記録されていませんでした',
      memory_not_smaller: '記憶が元のシーンより短くなりませんでした',
      provider_failed: 'モデルが利用できないか、エラーを返しました',
      timeout: 'モデルが時間内に応答しませんでした',
      context_limit: 'シーンがモデルのコンテキストに収まりませんでした',
    },
    safe: '今回の試行で作られた記憶は保存されていません。元のシーンとチェックポイントは無事です。',
    retry: command => `再試行：${command}。`,
    unknown: '圧縮の状態は不明です。「コンテキスト」で確認してください。',
    failure: '状態を表示できませんでした。「コンテキスト」で確認してください。',
  },

  notices: {
    unknownCommand: 'そのコマンドはわかりません。/menu を開いてください。',
    cancelled: '操作を中止しました。完成したシーンとチェックポイントは保存されています。',
    nothingToCompact: keep => `まだ圧縮するものがありません。直近の${keep}シーンは、常にそのまま残します。新しいシーンは作られません。`,
    nothingToCompactYet: keep => `まだ圧縮するものがありません。直近の${keep}シーンは、常にそのまま残します。`,
    textOnly: '今のところ、対応しているのはテキストメッセージだけです。/menu を開くか、登場人物の行動を書いてください。',
    truncated: '応答が出力トークンの上限に達したため、途中で途切れている可能性があります。受信したテキストは保存されています。/continue で物語を続けられます。',
    deliveryUnconfirmed: 'シーンは保存されましたが、配信を確認できませんでした。/last で、生成し直さずに表示できます。',
    contextLimit: 'シード、蓄積された記憶、直近のシーン、新しい入力のいずれかが、設定されたコンテキストのしきい値に収まりません。元のシーンとチェックポイントはすべて保存されています。入力を短くするか、/checkpoints から別の時点を開いてください。',
    compactionUnverified: command => `圧縮を検証できませんでした。元のシーンと完成したチェックポイントは保存されています。再試行：${command}。`,
    failed: command => `操作を完了できませんでした。完成したシーンとチェックポイントは保存されています。再試行：${command}。`,
    gpuNotConfigured: 'GPUレンタルの制御は、まだ設定されていません。/model で現在のモデルを確認できます。',
    gpuPaused: 'GPUが一時停止しました。/model を開いて起動してから、行動をもう一度送ってください。',
    drawing: '🎨 挿絵を描いています…',
    pictureFailed: '挿絵は描けませんでした。シーンは保存されています。',
    promptSummary: (chars, tokens, style) =>
      `🖼 プロンプト：${tokens === null ? '' : `${grouped(tokens)} トークン${style === null ? '' : `（うちスタイル ${grouped(style)}）`} · `}${grouped(chars)} 文字`,
    sampleFailed: 'サンプルは描けませんでした。少し時間をおいてもう一度お試しください。',
  },

  errors: {
    seedFormat: 'タイトル（100文字まで）、2026-08-02 20:00 形式の日時、世界の説明が必要です。それぞれ行を分けて書いてください。',
    seedGone: 'このシードはすでに削除されています。',
    pickBranch: '/seeds から物語のルートを選んでください。',
    pickStory: '/seeds から物語またはチェックポイントを選んでください。',
    checkpointGone: 'このチェックポイントはすでに削除されています。',
    branchGone: 'このルートはすでに削除されています。',
    branchGoneOpenSeeds: 'このルートはすでに削除されています。/seeds を開いてください。',
    jobRunning: '続きはすでに準備中です。リクエストが止まっている場合は、/cancel で中止できます。',
    sceneTime: 'モデルが正しい日時を示しませんでした。応答は記録されていません。続きをもう一度送ってください。',
    busy: 'すでに生成または圧縮を実行中です。応答を待つか、/cancel を押してから、メッセージをもう一度送ってください。',
    busyNewSeed: 'すでにシーンを執筆中です。応答を待つか、/cancel を押してから、シードを作成してください。',
    staleButton: 'このボタンは古くなっています。/menu を開いてください。',
    staleConfirmation: 'この確認は古くなっています。/seeds から削除をやり直してください。',
    gpuNotReady: 'GPUは今、準備ができていません。/model を開くと、起動や状態の確認ができます。その後、行動をもう一度送ってください。',
    unsupportedContent: 'メッセージに、対応していない内容が含まれています。シードや続きは、添付なしのテキストで送ってください。何も保存されていません。',
    draftChanged: '読み込み中に下書きが変更されました。ファイルは追加されていません。/new を開いて、もう一度送ってください。',
    otherDraft: 'このボタンは別の下書きのものです。最後に受け付けたパートの下にある「シードを保存」を使ってください。',
    draftNeedsText: 'シードの次のパートをテキストで送ってください。終わったら「シードを保存」を押してください。/cancel で入力をキャンセルできます。',
    draftTooLarge: 'このパートを加えると、下書き全体の上限（テキスト256 KiB）を超えます。追加されていません。これまでのパートは下書きに残っています。/cancel で入力をキャンセルできます。',
    draftClosed: 'この下書きは、すでに保存または破棄されています。新しいシードは /new で作成できます。',
    fileNeedsDraft: 'ファイルでシードを読み込むには、先に /new を開いてください。ファイルは物語に追加されていません。',
    fileFailed: 'ファイルを読み込めませんでした。下書きは変更されていません。もう一度ファイルを送ってください。',
    fileIncomplete: 'ファイル全体を読み込めませんでした。下書きは変更されていません。もう一度ファイルを送ってください。',
    fileTooLarge: 'ファイルが大きすぎます。ファイルと下書き全体の上限は、テキスト256 KiBです。',
    fileType: 'UTF-8の .txt または .md テキストファイルを送ってください。PDFとDOCXには、まだ対応していません。',
    fileEncoding: 'UTF-8として読み込めませんでした。ファイルをUTF-8で保存して、もう一度送ってください。下書きは変更されていません。',
    fileBinary: 'バイナリデータを含まない、空でない .txt または .md テキストファイルが必要です。下書きは変更されていません。',
    styleNeedsText: 'スタイルはテキストで、1通のメッセージで送ってください。変更せずに戻るには「↩️」を押すか、/cancel を送ってください。',
    styleTooLong: '長すぎます。スタイルは400文字以内にしてください。短くしてもう一度送ってください。',
    stylesFull: 'ライブラリには自分のスタイルがすでに10個あります。新しく追加するには、どれか1つを削除してください。',
    sampleOff: 'あなたのシーンにはまだ挿絵が有効になっていないため、サンプルは描けません。',
    sampleBusy: 'シーンはまだ執筆中です。届いてからサンプルを頼んでください。',
    sampleNoScene: 'サンプルは最新のシーンをもとに描きます。物語を始めると、最初のシーンのあとから頼めます。',
    sampleInFlight: 'サンプルを描いているところです。届いたら次のサンプルを頼めます。',
    lookNeedsText: '外見はテキストで、1通のメッセージで送ってください。変更せずに戻るには「↩️」を押すか、/cancel を送ってください。',
    lookTooLong: '長すぎます。外見は400文字以内にしてください。短くしてもう一度送ってください。',
    lookGone: 'この登場人物はもう物語にいないため、外見は保存されていません。/menu を開いてください。',
    portraitOff: 'あなたのシーンにはまだ挿絵が有効になっていないため、肖像は描けません。',
    portraitStale: 'この肖像はもう保存できません。古くなったか、そのあと外見が変わりました。新しく描いてください。',
    portraitInFlight: '頼まれた絵を描いているところです。届いたら肖像を頼めます。',
  },

  labels: {
    firstBranch: '始まり',
    seedCheckpoint: 'シード',
    forkBranch: from => `${from}から`,
    forkCheckpoint: '分岐点',
    scene: n => `シーン ${n}`,
    beforeCompaction: '圧縮前',
    afterCompaction: '圧縮後',
  },

  commands: {
    menu: '物語メニュー',
    seeds: '自分のシード',
    new: 'シードを作成',
    checkpoints: 'シーンとチェックポイント',
    continue: '物語を続ける',
    last: '最後のシーンを表示',
    context: 'コンテキストサイズとトークン数',
    compact: '初期のシーンを今すぐ記憶に圧縮',
    model: '現在のモデルと接続',
    language: '表示言語',
    style: 'シーンの挿絵のスタイル',
    gpu_pause: '作業の完了後にGPUを一時停止',
    gpu_start: 'レンタルGPUを起動',
    cancel: '入力や生成を中止',
  },
};
