// Korean interface catalog. Keys, arguments and the notes for translators are in ru.ts, which defines `Messages`.
//
// Glossary, one term per concept:
//   seed 시드 · story 이야기 · branch 분기 · checkpoint 체크포인트 · scene 장면 · memory 기억 (GPU memory: GPU 메모리)
//   compaction 압축, memory compaction 기억 압축 · retelling 요약 · context 컨텍스트, window 컨텍스트 창 · model 모델
//   continue 이어가기 · fork «Continue from here» 여기서 이어가기 · fork point 분기점 · line of events 흐름
//   draft 초안 · snapshot 스냅샷 · threshold 기준치 · verbatim 원문 그대로 · archive 보관함 · provider 제공자
//   job 작업 · pause 일시정지 · world time 이야기 속 시각 · character 인물 · token 토큰
// Style: 해요체 everywhere. Names are quoted “…” (format.quote); buttons named inside a sentence are quoted ‘…’.
// Counters are attached to the number (장면 3개, 5분, 1,200토큰); ASCII units keep a space (12 B, 256 KiB).
// A /command is never followed directly by a particle: it stands after a colon or before « 명령».

import type { Messages } from './ru.ts';

const grouped = (n: number) => String(Math.round(n)).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
// Picks a particle by how `text` ends, looking past closing quotes: `closed` after a final consonant, `open` after a
// vowel. Digits go by their Korean reading; a Latin ending counts as closed only for l, m, n and ng; the rest is open.
const josa = (text: string, closed: string, open: string) => {
  const word = text.replace(/[^\p{L}\p{N}]+$/u, '');
  const code = word.charCodeAt(word.length - 1);
  if (code >= 0xac00 && code <= 0xd7a3) return (code - 0xac00) % 28 ? closed : open;
  if (/\d$/.test(word)) return /[013678]$/.test(word) ? closed : open;
  return /(?:[lmn]|ng)$/i.test(word) ? closed : open;
};
// With the topic particle, which differs between the two forms.
const lastScenes = (n: number | null) => (n === null ? '최근 장면은' : `최근 장면 ${n}개는`);
const jobs = (n: number | null) => (n === null ? '알 수 없음' : `${n}개`);
const textSize = (label: string, tokens: number | null, chars: number) =>
  `${label}: ${tokens === null ? '토큰 수 알 수 없음' : `${grouped(tokens)}토큰`} · ${grouped(chars)}자`;

export const ko: Messages = {
  format: {
    number: n => grouped(n),
    quote: text => `“${text}”`,
    untitled: '제목 없음',
    untitledButton: '제목 없음',
    unknown: '알 수 없음',
  },

  count: {
    scenes: n => `장면 ${n}개`,
    stories: n => `이야기 ${n}개`,
    branches: n => `분기 ${n}개`,
    checkpoints: n => `체크포인트 ${n}개`,
    parts: n => `부분 ${n}개`,
    characters: n => `${grouped(n)}자`,
  },

  duration: {
    seconds: s => `${s}초`,
    minutes: (m, ss) => `${m}분 ${ss}초`,
    hours: (h, mm) => `${h}시간 ${mm}분`,
  },

  buttons: {
    menu: '🏠 메뉴',
    continue: '▶️ 이어가기',
    stop: '✖️ 중지',
    lastScene: '📄 마지막 장면',
    context: '📏 컨텍스트',
    model: '🤖 모델',
    checkpoints: '🔖 체크포인트',
    branches: '🌿 분기',
    seeds: '📚 시드',
    seedsCount: n => `📚 시드 (${n})`,
    newSeed: '➕ 새 시드',
    refresh: '🔄 새로고침',
    compactNow: '🗜 지금 압축',
    cancelScene: '✖️ 생성 취소',
    cancelCompaction: '✖️ 압축 취소',
    toCheckpoint: '◀️ 체크포인트로',
    previous: '⬅️ 이전',
    next: '다음 ➡️',
    keep: '↩️ 삭제 안 함',
    pictureStyle: '🎨 삽화 스타일',
    characters: '👤 인물',
  },

  common: {
    current: '✅ 현재',
    page: (page, pages) => `${page} / ${pages} 페이지`,
    storyName: (title, n) => `${title} · 이야기 ${n}`,
    noScenes: '아직 장면 없음',
    staleHint: '이미 삭제됐거나 오래된 화면일 수 있어요.',
    failure: '⚠️ 이 화면을 표시하지 못했어요.',
    failureHint: '메뉴로 돌아가 다시 시도해 주세요.',
    whatIsSeed: '시드는 세계, 인물, 시작 상황을 담은 설정이에요. 시드 하나로 이야기를 몇 개든 시작할 수 있어요.',
  },

  busy: {
    scene: {
      startOrDeleteSeed: '⏳ 지금 장면을 쓰고 있어요. 이야기 시작과 시드 삭제는 장면이 끝난 뒤에 할 수 있어요.',
      switchOrDeleteBranch: '⏳ 지금 장면을 쓰고 있어요. 분기 전환과 삭제는 장면이 끝난 뒤에 할 수 있어요.',
      fork: '⏳ 지금 장면을 쓰고 있어요. 체크포인트에서 이어가기는 장면이 끝난 뒤에 할 수 있어요.',
      compact: '⏳ 지금 장면을 쓰고 있어요. 이야기 압축은 장면이 끝난 뒤에 할 수 있어요.',
      deleteSeed: '⏳ 지금 장면을 쓰고 있어요. 시드 삭제는 장면이 끝난 뒤에 할 수 있어요.',
      deleteBranch: '⏳ 지금 장면을 쓰고 있어요. 분기 삭제는 장면이 끝난 뒤에 할 수 있어요.',
    },
    compact: {
      startOrDeleteSeed: '⏳ 지금 기억을 압축하고 있어요. 이야기 시작과 시드 삭제는 압축이 끝난 뒤에 할 수 있어요.',
      switchOrDeleteBranch: '⏳ 지금 기억을 압축하고 있어요. 분기 전환과 삭제는 압축이 끝난 뒤에 할 수 있어요.',
      fork: '⏳ 지금 기억을 압축하고 있어요. 체크포인트에서 이어가기는 압축이 끝난 뒤에 할 수 있어요.',
      compact: '⏳ 지금 기억을 압축하고 있어요. 이야기 압축은 이번 압축이 끝난 뒤에 할 수 있어요.',
      deleteSeed: '⏳ 지금 기억을 압축하고 있어요. 시드 삭제는 압축이 끝난 뒤에 할 수 있어요.',
      deleteBranch: '⏳ 지금 기억을 압축하고 있어요. 분기 삭제는 압축이 끝난 뒤에 할 수 있어요.',
    },
  },

  home: {
    title: '🏠 메뉴',
    unknownRoute: '⚠️ 이 화면은 더 이상 열 수 없어요. 메뉴를 보여 드릴게요.',
    gpu: status => `🖥 GPU: ${status}`,
    sceneJob: story => (story ? `⏳ ${story}에서 장면을 쓰고 있어요.` : '⏳ 장면을 쓰고 있어요.'),
    compactJob: story => (story ? `⏳ ${story}에서 기억을 압축하고 있어요.` : '⏳ 기억을 압축하고 있어요.'),
    sceneJobNote: '메뉴는 둘러볼 수 있어요. 삭제, 분기 전환, 새 장면 시작은 장면이 끝난 뒤에 할 수 있어요.',
    compactJobNote: '메뉴는 둘러볼 수 있어요. 삭제, 분기 전환, 새 장면 시작은 압축이 끝난 뒤에 할 수 있어요.',
    current: story => `📖 지금 이야기: ${story}`,
    branch: (name, progress) => `🌿 분기 ${name} · ${progress}`,
    howToContinue: '이어가려면 메시지를 보내면 돼요. 대사, 주인공의 행동, 작가로서의 지시 모두 좋아요. ‘이어가기’를 누르면 지시 없이 다음 장면을 써요.',
    noStory: '선택한 이야기가 없어요.',
    noStoryHint: '시드를 열어 새 이야기를 시작하거나 하던 이야기로 돌아가 보세요.',
    empty: '아직 아무것도 없어요.',
    createFirst: '첫 시드를 만들어 보세요. 설명을 메시지 하나 또는 여러 개로 보낸 뒤 저장하면 돼요.',
  },

  language: {
    title: '🌐 인터페이스 언어',
    note: '봇의 메뉴와 메시지 언어만 바뀌어요. 이야기의 언어는 시드와 내가 보내는 메시지가 정해요.',
  },

  variant: {
    button: '✏️ 프롬프트를 고쳐 변형 그리기',
    title: '✏️ 삽화에 쓸 내 프롬프트',
    note: max => `삽화 아래 메모에서 프롬프트를 복사해 고친 뒤 메시지 하나로 보내 주세요. 최대 ${max}자예요. 스타일까지 포함한 프롬프트 전체라서 아무것도 더하거나 빼지 않아요. 원래 삽화와 같은 설정, 같은 초기 노이즈로 그려서 프롬프트만 달라져요. 변형은 같은 장면 아래에 별도의 삽화로 도착해요.`,
    leave: '↩️ 그리지 않기',
    drawing: '🎨 변형을 그리는 중…',
    failed: '변형을 그리지 못했어요. 조금 뒤에 다시 시도해 주세요.',
  },

  pictureStyle: {
    title: '🎨 삽화 스타일',
    current: name => `지금: ${name}`,
    note: '스타일을 누르면 프롬프트를 보고, 그 스타일을 고르거나 예시를 요청할 수 있어요. 스타일은 앞으로 그릴 삽화에만 적용돼요. 이미 그린 삽화는 그대로예요. 인물의 외모(머리, 옷, 특징)는 바뀌지 않아요.',
    off: '아직 내 장면에는 삽화가 켜져 있지 않아요. 선택은 저장되고, 삽화가 켜지면 적용돼요.',
    standard: '⚙️ 기본',
    presets: {
      semi: '🖌 세미 리얼리즘',
      novel: '📖 비주얼 노벨',
      film: '🎬 영화 스틸',
      graphic: '🖋 그래픽 노블',
      watercolor: '💧 수채화',
    },
    own: name => `✍️ ${name}`,
    add: '➕ 새 스타일',
    chosen: '✅ 지금 삽화는 이 스타일로 그려져요.',
    prompt: '스타일 프롬프트(누르면 복사돼요):',
    choose: '✅ 이 스타일로 그리기',
    sample: '🖼 마지막 장면으로 예시 보기',
    sampleAll: '🖼 마지막 장면으로 모든 스타일 보기',
    edit: '✏️ 수정',
    remove: '🗑 삭제',
    back: '↩️ 스타일 목록으로',
    removeTitle: quotedName => `🗑 ${quotedName} 스타일을 삭제할까요?`,
    removeChosen: name => `지금 삽화는 이 스타일로 그려지고 있어요. 삭제하면 ${name} 스타일로 그려져요.`,
    removeYes: '🗑 네, 삭제할게요',
    removeNo: '↩️ 그대로 두기',
    newTitle: '➕ 새 삽화 스타일',
    editTitle: quotedName => `✏️ ${quotedName} 스타일`,
    inputNote: (max, nameMax) => `어떻게 그릴지 메시지 하나로 보내 주세요: 기법, 색, 빛, 분위기. 최대 ${max}자예요. 첫 줄에 이름을 쓸 수 있어요(최대 ${nameMax}자). 줄거리와 인물은 쓰지 마세요. 장면에서 가져와요. 삽화 모델은 영어를 가장 잘 이해해요.`,
    editNote: max => `새 내용을 메시지 하나로 보내 주세요. 최대 ${max}자예요. 첫 줄에 새 이름을 쓸 수 있어요. 쓰지 않으면 지금 이름이 그대로 남아요.`,
    example: '예:',
    exampleText: '촛불 아래 유화\nOil painting with visible impasto brushstrokes, warm candlelight and deep shadows.',
    copyHint: '어떤 스타일이든 카드에서 프롬프트를 복사해 고쳐 쓸 수 있어요.',
    nowText: '지금:',
    backToStyle: '↩️ 스타일로 돌아가기',
    sampleCaption: name => `스타일 예시: ${name}`,
    drawingSample: '🎨 예시를 그리는 중…',
    // `count` is how many styles are drawn, one picture each.
    drawingAll: (count: number) => `🎨 마지막 장면을 모든 스타일(${count}개)로 그리는 중이에요. 그림은 한 장씩 도착하고, 이야기에서 다음 행동을 하면 그리기가 멈춰요.`,
  },

  characters: {
    title: story => `👤 인물: ${story}`,
    note: '이 이야기의 삽화는 인물을 이렇게 그려요. 인물을 누르면 전체 설명을 보고, 외모를 고치거나 초상화를 그릴 수 있어요.',
    none: '인물은 이야기의 첫 삽화가 나온 뒤에 생겨요.',
    toStory: '📖 이야기로',
    cardTitle: (person, story) => `👤 ${person} · ${story}`,
    look: '장면 삽화에 쓰는 짧은 외모(누르면 복사돼요):',
    lookSize: (tokens, chars) => textSize('짧은 외모 텍스트', tokens, chars),
    lookOwn: '✍️ 직접 쓴 텍스트예요. 자세한 외모를 고치기 전까지 장면 삽화는 이걸 써요. 자세한 외모를 고치면 짧은 외모를 거기서 다시 줄여 만들어요.',
    lookPending: '⏳ 자세한 외모는 저장했지만 아직 짧은 외모로 줄이지 못했어요. 그동안 장면 삽화는 이전 외모를 써요. 이 이야기의 다음 삽화를 그리기 전에 봇이 줄여 둘게요.',
    details: '초상화를 그리는 자세한 외모(누르면 복사돼요):',
    detailsSize: (tokens, chars) => textSize('자세한 외모 텍스트', tokens, chars),
    clothesOfBranch: branch => `분기 ${branch}의 마지막 삽화 속 옷:`,
    clothesAtStart: '이 이야기의 삽화가 시작될 때의 옷:',
    clothesSize: (tokens, chars) => textSize('옷 텍스트', tokens, chars),
    noClothes: '아직 기록된 옷이 없어요.',
    clothesNote: '옷은 여기서 고치지 않아요. 옷은 이야기 속에서 바뀌고, 삽화는 장면에서 옷을 가져와요.',
    sizeNote: '숫자는 텍스트마다 따로 센 거예요. 프롬프트에는 장면 묘사와 스타일도 들어가요. 정확한 크기는 삽화 아래에 있어요.',
    scope: '외모를 고치면 이 이야기의 모든 분기에서 앞으로 그릴 삽화에 적용돼요. 이야기 본문, 기억, 이미 그린 삽화는 바뀌지 않아요. 지금 그리고 있는 삽화는 예전 외모로 나올 수 있어요.',
    portraitNone: details => `🖼 아직 초상화가 없어요. 초상화는 ${details ? '자세한 외모' : '짧은 외모'}대로 얼굴과 전신 체형을 그려서 참고 이미지를 고르기 쉽게 해 줘요.`,
    portraitKept: details => `🖼 초상화를 저장했어요. ${details ? '자세한 외모' : '짧은 외모'}대로 그린 얼굴과 체형이에요.`,
    portraitStale: details => `🖼 저장한 초상화는 이전 외모로 그린 거예요. 새로 그리면 ${details ? '자세한 외모' : '짧은 외모'}대로 얼굴과 체형을 볼 수 있어요.`,
    edit: '✏️ 짧은 외모 수정',
    editDetails: '✏️ 자세한 외모 수정',
    portrait: '🖼 초상화',
    back: '↩️ 인물 목록으로',
    editTitle: (person, story) => `✏️ 짧은 외모: ${person} · ${story}`,
    editNote: max => `새 짧은 외모를 메시지 하나로 보내 주세요: 얼굴, 머리, 체형, 키, 특징. 최대 ${max}자예요. 옷과 이름은 쓰지 마세요. 옷은 이야기가 바꾸고, 이름은 그대로 남아요. 삽화 모델은 영어를 가장 잘 이해해요.`,
    editKeepsDetails: '초상화는 계속 자세한 외모대로 그려요. 직접 쓴 짧은 외모는 자세한 외모를 다시 고칠 때까지, 거기서 줄여 만든 외모 대신 쓰여요.',
    detailsTitle: (person, story) => `✏️ 자세한 외모: ${person} · ${story}`,
    detailsNote: max => `자세한 외모를 메시지 하나로 보내 주세요. 어떤 언어로 써도 돼요: 성별, 숫자가 아닌 말로 쓴 나이, 피부색, 키와 체형, 머리, 얼굴, 특징. 최대 ${max}자예요. 옷은 쓰지 마세요. 옷은 장면에서 가져와요. 초상화는 이 텍스트를 쓴 그대로 그리고, 장면 삽화에 쓸 짧은 외모는 봇이 이걸 영어로 줄여서 만들어요. 삽화 모델은 영어를 가장 잘 이해해요.`,
    nowText: '지금:',
    backToCard: '↩️ 인물로 돌아가기',
    caption: person => `🖼 초상화: ${person}. 얼굴과 전신 체형을 단순하고 중립적인 옷차림으로 그렸어요.`,
    again: '🔄 다시 그리기',
    keep: '✅ 이걸로 저장',
    kept: person => `✅ 초상화를 저장했어요: ${person}. 장면 삽화에는 아직 쓰이지 않아요.`,
    drawing: '🎨 초상화를 그리는 중…',
    compressing: '⏳ 자세한 외모를 짧은 외모로 줄이는 중…',
    portraitFailed: '초상화를 그리지 못했어요. 조금 뒤에 다시 시도해 주세요.',
  },

  model: {
    title: '🤖 모델',
    noData: '아직 모델 정보가 없어요.',
    providers: {
      'claude-code': { short: 'Claude Code', full: 'Claude 구독으로 쓰는 Claude Code(자체 GPU 서버 아님)' },
      'llama-cpp': { short: '자체 서버', full: '자체 모델 서버(llama.cpp)' },
      'simple-serving': { short: '자체 서버', full: '자체 모델 서버(vLLM)' },
      'codex-cli': { short: 'Codex', full: 'ChatGPT 구독으로 쓰는 Codex CLI(자체 GPU 서버 아님)' },
      'openai-compatible': { short: '호스팅 API', full: 'OpenAI 형식의 호스팅 API(자체 GPU 서버 아님)' },
    },
    provider: full => `제공자: ${full}`,
    name: model => `모델: ${model}`,
    notes: {
      'claude-code': '모델은 우리가 임대한 GPU가 아니라 Claude 구독으로 실행돼요.',
      'llama-cpp': '자체 모델 서버예요. 서버 확인은 그래픽카드, GPU 메모리, 속도, 글의 품질을 측정하지 않아요.',
      'simple-serving': '자체 모델 서버예요. 서버 확인은 그래픽카드, GPU 메모리, 속도, 글의 품질을 측정하지 않아요.',
      'codex-cli': '모델은 우리가 임대한 GPU가 아니라 ChatGPT 구독으로 실행돼요. 이야기 텍스트는 외부 서비스로 전송돼요.',
      'openai-compatible': '모델은 우리가 임대한 GPU가 아니라 외부 제공자 쪽에서 실행돼요. 이야기 텍스트는 외부 서비스로 전송돼요.',
    },
    ready: time => `✅ 마지막 확인·응답 성공: ${time ?? '시각 알 수 없음'}.`,
    readyNote: '그 시점의 상태일 뿐, 계속 지켜보는 건 아니에요. 지금은 모델이 응답하지 않을 수도 있어요.',
    unavailable: time => `⛔ 확인 당시 사용할 수 없었어요: ${time ?? '시각 알 수 없음'}.`,
    unavailableNote: '이 상태가 이어지면 새 장면을 쓰지 못할 수 있어요.',
    configured: '⚪ 설정은 됐지만 아직 확인하지 않아서, 준비됐는지 알 수 없어요.',
    unknown: '❔ 상태를 알 수 없어요.',
    footer: '모델은 채팅이 아니라 봇 설정에서 골라요.',
    short: {
      ready: time => (time ? `응답 확인 ${time}` : '응답 확인'),
      unavailable: '확인 당시 사용 불가',
      configured: '미확인',
      unknown: '상태 알 수 없음',
    },
  },

  gpu: {
    title: '🖥 GPU — 모든 봇 사용자 공용',
    ready: n => `🟢 실행 중. 현재 모델 작업: ${jobs(n)}.`,
    autoPause: minutes => `모델 작업 없이 ${minutes}분이 지나면 자동으로 일시정지돼요. 마지막 작업이 끝난 때부터 세고, 메뉴를 둘러봐도 이 시간은 초기화되지 않아요.`,
    untilPause: minutes => `자동 일시정지까지 ≈${minutes}분.`,
    untilPauseSoon: '자동 일시정지까지 1분 미만.',
    draining: n => `⏳ 일시정지 준비 중: 모델 작업이 모두 끝나기를 기다려요(현재 작업: ${jobs(n)}).`,
    drainingNote: '일시정지 전까지 새 장면과 압축은 시작되지 않아요.',
    stopping: '⏳ 중지하는 중. 당분간 새 장면과 압축은 시작되지 않아요.',
    paused: '⏸ 일시정지됨: Vast가 중지를 확인했어요.',
    pausedNote: 'GPU 사용료는 더 이상 나가지 않지만, 디스크 요금은 계속 나가요.',
    starting: '⏳ 시작하는 중. 시간이 걸릴 수 있어요. Vast에서 빈 그래픽카드를 기다리고 모델을 예열해야 해요.',
    error: '⚠️ GPU 제어 오류. 일시정지됐다는 뜻은 아니에요. 계속 실행되며 요금이 나갈 수 있어요. ‘새로고침’을 눌러 주세요.',
    unknown: '❔ GPU 상태를 알 수 없어요. 일시정지됐거나 무료라는 뜻은 아니에요. ‘새로고침’을 눌러 주세요.',
    pauseHint: '‘GPU 일시정지’는 모든 사용자의 GPU를 멈춰요. 모델이 작업 중이면 모든 장면과 압축이 끝난 뒤에 멈춰요.',
    startHint: '‘GPU 시작’도 시간이 걸릴 수 있어요. 빈 그래픽카드를 찾고 모델을 예열해야 해요.',
    storageNote: '이야기와 체크포인트는 봇에 저장되어 있어서 일시정지해도 사라지지 않아요.',
    start: '▶️ GPU 시작',
    pause: '⏸ GPU 일시정지',
    short: {
      ready: n => `실행 중 · 작업: ${jobs(n)}`,
      draining: n => `일시정지 준비 중, 남은 작업: ${jobs(n)}`,
      stopping: '중지하는 중',
      paused: '일시정지됨',
      starting: '시작하는 중',
      error: '오류, ‘모델’을 열어 새로고침해 주세요',
      unknown: '상태 알 수 없음, ‘모델’을 열어 새로고침해 주세요',
    },
  },

  seeds: {
    title: '📚 시드',
    titleCount: n => `📚 시드: ${n}개`,
    none: '아직 시드가 없어요.',
    noStories: '이야기 없음',
    hint: '시드를 골라 이야기를 시작하거나 하던 이야기를 열어 보세요.',
  },

  seed: {
    notFound: '시드를 찾을 수 없어요.',
    title: name => `🌱 시드 ${name}`,
    start: time => `이야기 속 시작 시각: ${time}`,
    startStory: '▶️ 새 이야기 시작',
    stories: n => `📖 이 시드로 만든 이야기: ${n}개`,
    story: n => `이야기 ${n}`,
    storyButton: n => `📖 이야기 ${n}`,
    noStories: '아직 이야기가 없어요. ‘새 이야기 시작’을 누르면 이야기를 만들고 바로 첫 장면을 써요.',
    delete: '🗑 시드 삭제',
    all: '📚 모든 시드',
  },

  story: {
    notFound: '이야기를 찾을 수 없어요.',
    branches: n => `🌿 분기: ${n}개`,
    none: '분기가 없어요.',
    hint: '분기는 독립된 사건의 흐름이에요. 체크포인트에서 이야기를 이어가면 새 분기가 생기고, 기존 분기는 그대로 남아요.',
    tree: '🌳 이야기 트리',
    toSeed: '🌱 시드로',
  },

  tree: {
    root: '🌱 시작',
    run: (n, until) => `장면 ${n}개${until ? ` · ${until}까지` : ''}`,
    more: n => `… 그 외 ${n}개`,
    compaction: '🗜 기억 압축',
    branch: '분기',
    checkpoint: '체크포인트',
    legend: '🌿 분기 · 🗜 기억 압축 · 📍 내 체크포인트 · ✅ 현재 위치. 갈림길이나 표시가 없는 구간은 한 줄로 접혀 있고, 시각은 이야기 속 시각이에요. 구간의 장면 하나하나는 아래 분기별 장면 목록에서 볼 수 있어요.',
    scenes: branch => `📜 장면: ${branch}`,
    toStory: '📖 이야기로',
  },

  log: {
    title: name => `📜 분기 ${name}의 장면`,
    summary: n => `장면 ${n}개, 최신순`,
    compaction: '🗜 압축',
    truncated: '⚠️ 끊김',
    scene: '장면',
    none: '아직 장면이 없어요.',
    hint: '장면을 열면 읽거나 그 장면에서 새 분기로 이어갈 수 있어요.',
    newer: '⬆️ 더 최근',
    older: '더 이전 ⬇️',
    tree: '🌳 트리',
    toBranch: '🌿 분기로',
  },

  branch: {
    notFound: '분기를 찾을 수 없어요.',
    title: name => `🌿 분기 ${name}`,
    isCurrent: '✅ 현재 분기예요.',
    lastScene: '마지막 장면:',
    pickHint: '이 분기에서 플레이하려면 분기를 선택해 주세요. 마지막 장면을 보여 드릴게요.',
    play: '✅ 이 분기에서 플레이',
    scenes: '📜 분기의 장면',
    checkpoints: n => `🔖 체크포인트 (${n})`,
    delete: '🗑 분기 삭제',
    all: '◀️ 모든 분기',
  },

  checkpoints: {
    title: (name, n) => `🔖 분기 ${name}의 체크포인트: ${n}개`,
    hint: '체크포인트를 열면 장면을 다시 읽고, 원하면 그 장면에서 새 분기로 이어갈 수 있어요. 최신순이에요.',
    none: '아직 체크포인트가 없어요. 장면이 끝날 때마다 하나씩 생겨요.',
    newer: '⬅️ 더 최근',
    older: '더 이전 ➡️',
    toBranch: '◀️ 분기로',
  },

  checkpoint: {
    notFound: '체크포인트를 찾을 수 없어요.',
    untitled: '체크포인트',
    branch: (name, story) => `🌿 분기 ${name} · ${story}`,
    isHead: '✅ 현재 분기의 마지막 장면이에요.',
    atStart: '🌱 이야기의 시작이에요. 아직 장면이 없어요.',
    start: time => `이야기 속 시작 시각: ${time}`,
    seedMissing: '시드를 불러올 수 없어요.',
    textMissing: '장면 텍스트를 불러올 수 없어요.',
    input: text => `✍️ 입력: ${text}`,
    truncated: '⚠️ 생성 도중 장면이 끊겼어요.',
    forkNote: name => `‘여기서 이어가기’를 누르면 이 시점부터 새 분기가 생겨요. 분기 ${name}${josa(name, '은', '는')} 그대로 남아요.`,
    fork: '🌿 여기서 이어가기',
    back: '◀️ 체크포인트',
  },

  context: {
    title: '📏 컨텍스트',
    titleOf: label => `📏 컨텍스트: ${label}`,
    checkpoint: '체크포인트',
    branch: '현재 분기',
    none: '📏 컨텍스트: 아직 데이터가 없어요.',
    noStory: '선택한 이야기가 없어요. 시드를 열고 분기를 골라 주세요.',
    currentBranch: '📏 현재 분기의 컨텍스트',
    noData: '컨텍스트 크기 데이터가 아직 없어요.',
    noCheckpointData: '이 체크포인트의 크기 데이터가 아직 없어요.',
    atCheckpoint: '이 체크포인트 시점의 크기예요.',
    atBranch: '현재 분기, 마지막으로 저장된 상태예요.',
    duringCompaction: '⏳ 기억을 압축하고 있어요. 여기에는 압축 전 상태가 보여요.',
    duringScene: '⏳ 지금 쓰고 있는 장면은 여기에 포함되지 않았어요.',
    window: (limit, reserve) => `컨텍스트 창: 응답 포함 ${limit}토큰${reserve ? `, 응답용 예약 ${reserve}토큰` : ''}.`,
    windowUnknown: '컨텍스트 창: 크기를 알 수 없어요.',
    nextRequest: (tokens, share) => `다음 요청 ≈${tokens}토큰${share ? ` (창의 ≈${share})` : ''}: 스냅샷, 봇 규칙, 지시 없는 ‘이어가기’ 기준이에요. 입력이 길면 그만큼 늘어나요.`,
    nextRequestUnknown: '다음 요청: 추정치가 없어요.',
    estimateFromUsage: '이 흐름에서 마지막으로 측정한 요청에 맞춰 보정한 추정치예요.',
    estimateFromBytes: '대략적인 추정: UTF-8 바이트 ÷ 4에 시스템 영역 여유분을 더한 값이에요.',
    budget: (input, limit) => `입력 예산(창에서 응답 예약분 제외): ${limit}토큰 중 ${input ? `≈${input}토큰 사용` : '사용량 알 수 없음'}.`,
    remaining: tokens => `남은 예산 ≈${tokens}토큰.`,
    exhausted: '⚠️ 추정상 입력 예산을 이미 다 썼어요.',
    forecastNote: '정확한 계산이 아니라 예측이에요. 실제 입력은 모델이 응답을 시작할 때, 텍스트를 보여 주기 전에 다시 확인해요.',
    autoCompaction: (threshold, keep) => `자동 압축: 입력이 ≈${threshold}토큰에 이르면 실행돼요${keep === null ? '' : `. ${lastScenes(keep)} 원문 그대로 남아요`}.`,
    autoCompactionNote: '측정된 토큰 수에 따라 사전 추정치가 바뀔 수 있어요. 압축 전후로 체크포인트가 저장되고 원본 장면은 보관함에 남아요.',
    snapshot: '스냅샷 (B는 정확한 값, ≈는 UTF-8 바이트 ÷ 4로 정확한 토큰 수가 아님):',
    bytes: n => `${n} B`,
    bytesUnknown: '크기 알 수 없음',
    tokens: n => `≈${n}토큰`,
    tokensUnknown: '토큰 수 알 수 없음',
    seed: size => `• 시드: ${size}`,
    memory: size => `• 기억: ${size}`,
    memoryEmpty: '비어 있음, 아직 압축한 적 없음',
    prefix: size => `= 시드 + 기억: ${size}`,
    tail: (scenes, size) => `• 압축되지 않은 장면${scenes === null ? '' : ` (${scenes}개)`}: ${size}`,
    whole: size => `= 스냅샷 전체: ${size}`,
    lastRequest: (input, output, total) => `마지막 요청(측정값): 입력 ${input} · 출력 ${output} · 합계 ${total}`,
    lastRequestNone: '마지막 요청(측정값): 측정 기록 없음',
    lastRequestNote: '입력에는 캐시가 포함되고, 출력에는 모델의 숨은 추론이 포함될 수 있어요. 요청 한 번의 수치일 뿐, 지금까지의 총사용량도 다음 요청의 예측도 아니에요.',
    compactNote: keep => `🗜 ‘지금 압축’은 기준치를 기다리지 않고 오래된 장면을 기억으로 요약해요. ${lastScenes(keep)} 원문 그대로 남고, 원본 장면은 보관함에 보존되며, 압축 전후로 체크포인트가 저장돼요. 압축은 새 장면을 쓰지 않아요.`,
  },

  scenePrefix: {
    context: (percent, rough) => `📏 컨텍스트 ≈ ${percent}%${rough ? ', 대략적인 추정' : ''}`,
    contextBelowOne: rough => `📏 컨텍스트 1% 미만${rough ? ', 대략적인 추정' : ''}`,
  },

  deletion: {
    note: '삭제하면 되돌릴 수 없어요. 삭제된 장면의 삽화는 보낸 지 이틀이 안 됐다면 봇이 이 채팅에서 지워요. 채팅에 있는 장면 텍스트는 남아요.',
    seedTitle: name => `🗑 시드 ${name}${josa(name, '을', '를')} 삭제할까요?`,
    withSeed: '함께 영구 삭제되는 항목:',
    scenesAndCheckpoints: n => `장면 ${n}개와 모든 체크포인트`,
    includesCurrent: '현재 이야기 포함',
    onlySeed: '이 시드로 만든 이야기가 없어서 시드만 삭제돼요.',
    confirmAll: '🗑 네, 모두 삭제',
    confirmSeed: '🗑 네, 시드 삭제',
    branchTitle: name => `🗑 분기 ${name}${josa(name, '을', '를')} 삭제할까요?`,
    onlyBranch: '하나뿐인 분기라서 이야기 전체가 삭제돼요:',
    seedStays: name => `시드 ${name}${josa(name, '은', '는')} 남아요. 이 시드로 새 이야기를 시작할 수 있어요.`,
    forever: '영구 삭제되는 항목:',
    checkpointsOfBranch: n => `이 분기의 체크포인트 ${n}개`,
    scenesOnlyHere: n => `다른 분기에 없는 장면 ${n}개`,
    scenesStay: '장면은 삭제되지 않아요: 모두 다른 분기에도 있어요',
    kept: n => `남는 항목: 이 이야기의 다른 분기 ${n}개.`,
    isCurrent: '⚠️ 현재 분기예요. 삭제한 뒤 다른 분기를 골라 주세요.',
    confirmBranch: '🗑 네, 분기 삭제',
    confirmStory: '🗑 네, 이야기 삭제',
  },

  newSeed: {
    title: '➕ 새 시드',
    steps: [
      '설명을 메시지 하나 또는 여러 개로 보내 주세요:',
      '1) 첫째 줄: 제목, 100자 이내',
      '2) 둘째 줄: 이야기 속 시작 날짜와 시각, YYYY-MM-DD HH:MM 형식(연-월-일 시:분)',
      '3) 그다음: 세계, 인물, 시작 상황',
      '',
      '긴 글은 여러 메시지로 나눠 보내도 돼요. 모두 하나의 초안으로 합쳐져요.',
      '📎 .txt / .md 파일을 첨부해도 돼요(UTF-8, 초안 전체 256 KiB 이내). 첫 줄들에 제목과 날짜까지 담은 완성본이어도 되고, 설명만 담아도 돼요. 설명만 담았다면 제목과 날짜를 파일보다 먼저 메시지로 보내 주세요. 파일 캡션은 반영되지 않고, PDF와 DOCX는 쓸 수 없어요.',
      '다 보냈으면 ‘💾 시드 저장’을 눌러 주세요. 그 전에는 시드가 저장되지 않고 장면도 쓰지 않아요.',
    ].join('\n'),
    exampleLabel: '예시:',
    example: [
      '세상 끝의 등대',
      '2026-08-02 20:00',
      '북쪽 섬, 늦여름. 스물일곱 살 미라는 등대지기로 첫 저녁을 맞는다. 등불이 켜진 빈 배 한 척이 선착장으로 떠밀려 온다.',
    ].join('\n'),
    compactRunning: '⏳ 앞서 시작한 기억 압축이 아직 진행 중이에요.',
    sceneRunning: '⏳ 앞서 시작한 장면을 아직 쓰고 있어요.',
    cancel: '✖️ 취소',
  },

  draft: {
    title: '📝 시드 초안 — 아직 저장 전',
    received: (parts, characters) => `받은 내용: 부분 ${parts}개 · ${grouped(characters)}자`,
    more: '메시지나 .txt / .md 파일을 더 보내면 설명에 이어 붙여요.',
    saveHint: '다 보냈으면 ‘💾 시드 저장’을 눌러 주세요. 지금도, 저장할 때도 장면은 쓰지 않아요. 이야기는 따로 시작해요.',
    menuNote: '메뉴와 다른 버튼은 초안을 저장하거나 취소한 뒤에 다시 쓸 수 있어요.',
    save: '💾 시드 저장',
    discard: '🗑 초안 취소',
  },

  wait: {
    ahead: n => `모델 대기열에서 앞에 ${n}건이 있습니다.`,
    queued: n => `⏳ 모델 대기열: 앞에 ${n}건.`,
    next: '⏳ 차례가 되었습니다.',
    reading: '📖 모델이 이야기를 읽고 있습니다. 곧 쓰기 시작합니다…',
  },
  compact: {
    title: '🗜 기억 압축',
    titleAutomatic: '🗜 새 장면 전 기억 압축',
    now: {
      queued: '⏳ 지금: 차례를 기다리는 중',
      extracting: '⏳ 지금: 모델이 장면에서 기억을 추출하는 중',
      validating: '⏳ 지금: 기억 구조와 장면 참조를 검증하는 중',
      saving: '⏳ 지금: 기억과 체크포인트를 저장하는 중',
    },
    steps: { queued: '대기', extracting: '추출', validating: '검증', saving: '저장' },
    elapsed: time => `경과: ${time}`,
    scope: (scenes, kept) => `이번 압축 대상 장면: ${scenes}개. ${lastScenes(kept)} 건드리지 않아요.`,
    repair: scenes => `↩️ 빠진 장면 추가 추출: ${scenes}개.`,
    memoryJson: characters => `기억 JSON: ${grouped(characters)}자`,
    extraJson: characters => `추가 JSON: ${grouped(characters)}자`,
    live: '이 메시지는 진행 상황에 따라 갱신돼요.',
    cancelAutomatic: '✖️ 취소',
    done: time => `✅ 압축 완료${time ? ` · ${time}` : ''}`,
    summary: (scenes, facts) => `요약한 장면: ${scenes}개, 기억에 담긴 사실: ${facts}개.`,
    summaryScenes: scenes => `요약한 장면: ${scenes}개.`,
    summaryFacts: facts => `기억에 담긴 사실: ${facts}개.`,
    repaired: scenes => `빠진 장면 ${scenes}개를 보충했고, 참조 검증을 통과했어요.`,
    kept: kept => `${lastScenes(kept)} 그대로 남았어요. 원본 장면은 보존되어 있고, 압축 전후에 체크포인트가 있어요.`,
    continues: '이야기는 계속돼요. 이어서 새 장면을 써요.',
    failed: time => `⚠️ 압축 실패${time ? ` · ${time}` : ''}`,
    cancelled: time => `✖️ 압축 취소됨${time ? ` · ${time}` : ''}`,
    reason: reason => `원인: ${reason}.`,
    reasons: {
      output_limit: '요약이 모델의 응답 한도를 넘었어요',
      finish_reason: '모델이 응답을 중간에 끊었어요',
      json: '모델이 요구한 형식으로 답하지 않았어요',
      shape: '모델의 응답이 구조 검증을 통과하지 못했어요',
      fact: '사실 하나가 검증을 통과하지 못했어요',
      source: '사실이 이번 압축에 없는 장면을 참조했어요',
      coverage: '요약에 빠진 장면이 있어요',
      evidence: '근거 참조가 검증을 통과하지 못했어요',
      quote: '인용문을 원본 장면에서 찾지 못했어요',
      conflict: '발견된 모순이 정해진 형식대로 기록되지 않았어요',
      memory_not_smaller: '기억이 원본 장면보다 짧아지지 않았어요',
      provider_failed: '모델을 쓸 수 없거나 모델이 오류를 반환했어요',
      timeout: '모델이 제시간에 응답하지 않았어요',
      context_limit: '장면이 모델의 컨텍스트에 들어가지 않았어요',
    },
    safe: '이번 시도의 기억은 저장되지 않았어요. 원본 장면과 체크포인트는 그대로예요.',
    retry: command => `다시 시도: ${command}`,
    unknown: '압축 상태를 알 수 없어요. ‘컨텍스트’에서 확인해 주세요.',
    failure: '상태를 표시하지 못했어요. ‘컨텍스트’에서 확인해 주세요.',
  },

  notices: {
    unknownCommand: '모르는 명령이에요. 메뉴 열기: /menu',
    cancelled: '작업을 취소했어요. 완성된 장면과 체크포인트는 저장되어 있어요.',
    nothingToCompact: keep => `아직 압축할 내용이 없어요. 최근 장면 ${keep}개는 항상 원문 그대로 둬요. 새 장면은 쓰지 않아요.`,
    nothingToCompactYet: keep => `아직 압축할 내용이 없어요. 최근 장면 ${keep}개는 항상 원문 그대로 둬요.`,
    textOnly: '지금은 텍스트 메시지만 지원해요. /menu 명령으로 메뉴를 열거나 인물의 행동을 적어 보내 주세요.',
    truncated: '응답이 출력 토큰 한도에 닿아 중간에 끊겼을 수 있어요. 받은 텍스트는 저장했어요. 이야기 이어가기: /continue',
    deliveryUnconfirmed: '장면은 저장됐지만 전송이 확인되지 않았어요. 새로 생성하지 않고 다시 보기: /last',
    contextLimit: '시드, 쌓인 기억, 최근 장면 또는 새 입력이 설정된 컨텍스트 기준치에 들어가지 않아요. 원본 장면과 체크포인트는 모두 저장되어 있어요. 입력을 줄이거나 /checkpoints 명령으로 다른 시점을 열 수 있어요.',
    compactionUnverified: command => `압축을 검증하지 못했어요. 원본 장면과 완성된 체크포인트는 저장되어 있어요. 다시 시도: ${command}.`,
    failed: command => `작업을 끝내지 못했어요. 완성된 장면과 체크포인트는 저장되어 있어요. 다시 시도: ${command}.`,
    gpuNotConfigured: 'GPU 임대 제어가 아직 설정되지 않았어요. 현재 모델 보기: /model',
    modelServiceSeparate: '모델 서비스는 이 채팅이 아니라 따로 시작돼요. 현재 모델 보기: /model',
    modelUnavailable: '모델 서비스를 지금 사용할 수 없어요. 서비스가 다시 작동하면 이야기를 이어갈 수 있어요.',
    gpuPaused: 'GPU가 일시정지됐어요. /model 명령으로 GPU를 시작한 뒤 행동을 다시 보내 주세요.',
    drawing: '🎨 삽화를 그리는 중…',
    pictureFailed: '삽화를 그리지 못했어요. 장면은 저장되어 있어요.',
    promptSummary: (chars, tokens, style) =>
      `🖼 프롬프트: ${tokens === null ? '' : `${grouped(tokens)}토큰${style === null ? '' : ` (스타일 ${grouped(style)})`} · `}${grouped(chars)}자`,
    sampleFailed: '예시를 그리지 못했어요. 조금 뒤에 다시 시도해 주세요.',
  },

  errors: {
    seedFormat: '제목(100자 이내), 2026-08-02 20:00 형식의 날짜, 세계 설명이 필요해요. 각각 새 줄에 적어 주세요.',
    seedGone: '이미 삭제된 시드예요.',
    pickBranch: '/seeds 명령으로 이야기의 분기를 골라 주세요.',
    pickStory: '/seeds 명령으로 이야기나 체크포인트를 골라 주세요.',
    checkpointGone: '이미 삭제된 체크포인트예요.',
    branchGone: '이미 삭제된 분기예요.',
    branchGoneOpenSeeds: '이미 삭제된 분기예요. 시드 목록 열기: /seeds',
    jobRunning: '다음 장면을 이미 준비하고 있어요. 요청이 멈춘 것 같으면 /cancel 명령으로 취소할 수 있어요.',
    sceneTime: '모델이 올바른 날짜와 시각을 알려 주지 않았어요. 응답은 저장되지 않았어요. 이어갈 내용을 다시 보내 주세요.',
    busy: '이미 장면 생성이나 압축이 진행 중이에요. 응답을 기다리거나 /cancel 명령으로 취소한 뒤 메시지를 다시 보내 주세요.',
    busyNewSeed: '이미 장면을 쓰고 있어요. 응답을 기다리거나 /cancel 명령으로 취소한 뒤 시드를 만들어 주세요.',
    staleButton: '오래된 버튼이에요. 메뉴 열기: /menu',
    staleConfirmation: '오래된 확인 화면이에요. /seeds 명령에서 삭제를 다시 시작해 주세요.',
    gpuNotReady: 'GPU가 아직 준비되지 않았어요. /model 명령으로 GPU를 시작하거나 상태를 확인한 뒤 행동을 다시 보내 주세요.',
    unsupportedContent: '메시지에 지원하지 않는 내용이 있어요. 시드나 이어갈 내용을 첨부 없이 텍스트로 보내 주세요. 아무것도 저장되지 않았어요.',
    draftChanged: '파일을 받는 동안 초안이 바뀌었어요. 파일은 추가되지 않았어요. /new 명령을 열고 파일을 다시 보내 주세요.',
    otherDraft: '다른 초안의 버튼이에요. 마지막으로 받은 부분 아래의 ‘시드 저장’을 눌러 주세요.',
    draftNeedsText: '시드의 다음 부분을 텍스트로 보내 주세요. 다 보냈으면 ‘시드 저장’을 눌러 주세요. 입력 취소: /cancel',
    draftTooLarge: '이 부분을 더하면 초안 전체 한도인 텍스트 256 KiB를 넘어요. 이 부분은 추가되지 않았고, 앞서 보낸 부분은 초안에 남아 있어요. 입력 취소: /cancel',
    draftClosed: '이미 저장했거나 취소한 초안이에요. 새 시드 만들기: /new',
    fileNeedsDraft: '시드를 파일로 올리려면 먼저 /new 명령을 열어 주세요. 파일은 이야기에 추가되지 않았어요.',
    fileFailed: '파일을 읽지 못했어요. 초안은 그대로예요. 파일을 다시 보내 주세요.',
    fileIncomplete: '파일을 끝까지 읽지 못했어요. 초안은 그대로예요. 파일을 다시 보내 주세요.',
    fileTooLarge: '파일이 너무 커요. 파일과 초안 전체의 한도는 텍스트 256 KiB예요.',
    fileType: 'UTF-8로 인코딩된 .txt 또는 .md 텍스트 파일을 보내 주세요. PDF와 DOCX는 아직 지원하지 않아요.',
    fileEncoding: 'UTF-8로 읽지 못했어요. 파일을 UTF-8로 저장해 다시 보내 주세요. 초안은 그대로예요.',
    fileBinary: '바이너리 데이터가 없고 비어 있지 않은 .txt 또는 .md 텍스트 파일이 필요해요. 초안은 그대로예요.',
    styleNeedsText: '스타일을 텍스트 메시지 하나로 보내 주세요. 바꾸지 않고 나가려면 ‘↩️’를 누르거나 /cancel을 보내 주세요.',
    styleTooLong: '너무 길어요. 스타일은 400자 안에 들어가야 해요. 줄여서 다시 보내 주세요.',
    stylesFull: '보관함에 나만의 스타일이 이미 10개 있어요. 새로 추가하려면 하나를 삭제해 주세요.',
    sampleOff: '아직 내 장면에는 삽화가 켜져 있지 않아서 예시를 그릴 수 없어요.',
    sampleBusy: '장면을 아직 쓰고 있어요. 장면이 도착하면 예시를 요청해 주세요.',
    sampleNoScene: '예시는 마지막 장면으로 그려요. 이야기를 시작하면 첫 장면 뒤부터 예시를 요청할 수 있어요.',
    sampleInFlight: '이미 예시를 그리고 있어요. 도착하면 다음 예시를 요청할 수 있어요.',
    promptNeedsText: '프롬프트를 텍스트 메시지 하나로 보내 주세요. 바꾸지 않고 나가려면 ‘↩️’를 누르거나 /cancel을 보내 주세요.',
    promptTooLong: '너무 길어요. 프롬프트는 4000자 안에 들어가야 해요. 줄여서 다시 보내 주세요.',
    variantOff: '아직 내 장면에는 삽화가 켜져 있지 않아서 변형을 그릴 수 없어요.',
    variantGone: '이 삽화의 변형은 더 이상 그릴 수 없어요. 장면이 삭제되었어요.',
    variantChanged: '그 뒤로 삽화 모델이나 그 설정이 바뀌어서 예전 것으로는 이 삽화를 더 이상 다시 그릴 수 없어요. 새것으로 그리면 프롬프트 말고도 달라지는 게 생기니 그리지 않아요.',
    variantBusy: '장면을 아직 쓰고 있어요. 장면이 도착하면 변형을 요청해 주세요.',
    variantInFlight: '이미 변형을 그리고 있어요. 도착하면 다음 변형을 요청할 수 있어요.',
    lookNeedsText: '외모를 텍스트 메시지 하나로 보내 주세요. 바꾸지 않고 나가려면 ‘↩️’를 누르거나 /cancel 명령을 보내 주세요.',
    lookTooLong: '너무 길어요. 외모는 400자 안에 들어가야 해요. 줄여서 다시 보내 주세요.',
    lookGone: '이 인물은 이제 이야기에 없어서 외모를 저장하지 못했어요. 메뉴 열기: /menu',
    detailsNeedsText: '자세한 외모를 텍스트 메시지 하나로 보내 주세요. 바꾸지 않고 나가려면 ‘↩️’를 누르거나 /cancel 명령을 보내 주세요.',
    detailsTooLong: '너무 길어요. 자세한 외모는 1000자 안에 들어가야 해요. 줄여서 다시 보내 주세요.',
    detailsGone: '이 인물은 이제 이야기에 없어서 자세한 외모를 저장하지 못했어요. 메뉴 열기: /menu',
    portraitOff: '아직 내 장면에는 삽화가 켜져 있지 않아서 초상화를 그릴 수 없어요.',
    portraitStale: '이 초상화는 이제 저장할 수 없어요. 너무 오래됐거나 그 뒤로 외모가 바뀌었어요. 새로 그려 주세요.',
    portraitInFlight: '요청한 그림을 이미 그리고 있어요. 그림이 도착하면 초상화를 요청할 수 있어요.',
  },

  labels: {
    firstBranch: '시작',
    seedCheckpoint: '시드',
    forkBranch: from => `${from}부터`,
    forkCheckpoint: '분기점',
    scene: n => `장면 ${n}`,
    beforeCompaction: '압축 전',
    afterCompaction: '압축 후',
  },

  commands: {
    menu: '이야기 메뉴',
    seeds: '내 시드',
    new: '시드 만들기',
    checkpoints: '장면과 체크포인트',
    continue: '이야기 이어가기',
    last: '마지막 장면 보기',
    context: '컨텍스트 크기와 토큰 수',
    compact: '초반 장면을 지금 기억으로 압축',
    model: '현재 모델과 연결',
    language: '인터페이스 언어',
    style: '장면 삽화 스타일',
    gpu_pause: '작업이 끝나면 GPU 일시정지',
    gpu_start: '임대한 GPU 시작',
    cancel: '입력 또는 생성 취소',
  },
};
