// Simplified Chinese (zh-Hans) interface catalog. Keys, arguments and the notes for translators are in ru.ts, which
// defines `Messages`.
//
// Glossary, one term per concept:
//   seed 种子 · story 故事 · branch 分支 · checkpoint 存档点 · scene 场景 · last scene 最新场景 · draft 草稿
//   memory 记忆 · compaction 压缩 (记忆压缩) · verbatim 保留原文 · archive 归档 · snapshot 快照 · context 上下文
//   window 窗口 · model 模型 · provider 提供方 · model job 模型任务 · token stays «token» · world time 故事内时间
//   fork / continue from here 从这里继续 (the point itself: 分岔点) · start of a story 开端
// Quotes are “” everywhere, for names and for button names inside sentences. The user is 你. Sentences take
// full-width punctuation; a number, a /command or a Latin word next to Chinese text is set off with a space.
// Chinese has no plurals, so a count is the number with a measure word.

import type { Messages } from './ru.ts';

const grouped = (n: number) => String(Math.round(n)).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
const sceneCount = (n: number) => `${n} 个场景`;
const lastScenes = (n: number | null) => (n === null ? '最近的场景' : `最近 ${sceneCount(n)}`);
const jobs = (n: number | null) => (n === null ? '未知' : String(n));

export const zh: Messages = {
  format: {
    number: n => grouped(n),
    quote: text => `“${text}”`,
    untitled: '未命名',
    untitledButton: '未命名',
    unknown: '未知',
  },

  count: {
    scenes: n => sceneCount(n),
    stories: n => `${n} 个故事`,
    branches: n => `${n} 个分支`,
    checkpoints: n => `${n} 个存档点`,
    parts: n => `${n} 个部分`,
    characters: n => `${n} 个字符`,
  },

  duration: {
    seconds: s => `${s} 秒`,
    minutes: (m, ss) => `${m} 分 ${ss} 秒`,
    hours: (h, mm) => `${h} 小时 ${mm} 分`,
  },

  buttons: {
    menu: '🏠 菜单',
    continue: '▶️ 继续',
    stop: '✖️ 停止',
    lastScene: '📄 最新场景',
    context: '📏 上下文',
    model: '🤖 模型',
    checkpoints: '🔖 存档点',
    branches: '🌿 分支',
    seeds: '📚 种子',
    seedsCount: n => `📚 种子 (${n})`,
    newSeed: '➕ 新建种子',
    refresh: '🔄 刷新',
    compactNow: '🗜 立即压缩',
    cancelScene: '✖️ 取消生成',
    cancelCompaction: '✖️ 取消压缩',
    toCheckpoint: '◀️ 返回存档点',
    previous: '⬅️ 上一页',
    next: '下一页 ➡️',
    keep: '↩️ 不删除',
    pictureStyle: '🎨 插图风格',
  },

  common: {
    current: '✅ 当前',
    page: (page, pages) => `第 ${page} / ${pages} 页`,
    storyName: (title, n) => `${title} · 故事 ${n}`,
    noScenes: '还没有场景',
    staleHint: '它可能已被删除，或者这个页面已经过期。',
    failure: '⚠️ 无法显示这个页面。',
    failureHint: '回到菜单再试一次。',
    whatIsSeed: '种子就是世界、角色和开场情境。同一个种子可以开始任意多个故事。',
  },

  busy: {
    scene: {
      startOrDeleteSeed: '⏳ 正在写场景：写完后才能开始故事或删除种子。',
      switchOrDeleteBranch: '⏳ 正在写场景：写完后才能切换或删除分支。',
      fork: '⏳ 正在写场景：写完后才能从存档点继续。',
      compact: '⏳ 正在写场景：写完后才能压缩故事。',
      deleteSeed: '⏳ 正在写场景：写完后才能删除种子。',
      deleteBranch: '⏳ 正在写场景：写完后才能删除分支。',
    },
    compact: {
      startOrDeleteSeed: '⏳ 正在压缩记忆：完成后才能开始故事或删除种子。',
      switchOrDeleteBranch: '⏳ 正在压缩记忆：完成后才能切换或删除分支。',
      fork: '⏳ 正在压缩记忆：完成后才能从存档点继续。',
      compact: '⏳ 正在压缩记忆：完成后才能再次压缩。',
      deleteSeed: '⏳ 正在压缩记忆：完成后才能删除种子。',
      deleteBranch: '⏳ 正在压缩记忆：完成后才能删除分支。',
    },
  },

  home: {
    title: '🏠 菜单',
    unknownRoute: '⚠️ 这个页面已经不可用了。这是菜单。',
    gpu: status => `🖥 GPU：${status}`,
    sceneJob: story => `⏳ 正在写场景${story ? `：${story}` : ''}。`,
    compactJob: story => `⏳ 正在压缩记忆${story ? `：${story}` : ''}。`,
    sceneJobNote: '可以浏览菜单；删除、切换分支和开始新场景要等它写完。',
    compactJobNote: '可以浏览菜单；删除、切换分支和开始新场景要等压缩完成。',
    current: story => `📖 当前：${story}`,
    branch: (name, progress) => `🌿 分支${name} · ${progress}`,
    howToContinue: '想继续，直接发消息就行：一句台词、主角的行动，或作者的指示。“继续”会不带任何指示地写出下一个场景。',
    noStory: '还没有选择故事。',
    noStoryHint: '打开一个种子，开始新故事或回到已开始的故事。',
    empty: '这里还是空的。',
    createFirst: '创建第一个种子：用一条或多条消息发来描述，然后保存。',
  },

  language: {
    title: '🌐 界面语言',
    note: '只会改变菜单和机器人消息的语言。故事的语言由种子和你发的消息决定。',
  },

  pictureStyle: {
    title: '🎨 插图风格',
    current: name => `当前：${name}`,
    note: '点一个风格，可以查看它的提示词、选用它，或者请求一张示例。风格只影响之后的插图，已经画好的保持不变。人物的外貌（发型、服装、特征）不会改变。',
    off: '你的场景还没有开启插图。选择会被保存，开启后生效。',
    standard: '⚙️ 标准',
    presets: {
      semi: '🖌 半写实',
      novel: '📖 视觉小说',
      film: '🎬 电影剧照',
      graphic: '🖋 图像小说',
      watercolor: '💧 水彩',
    },
    own: name => `✍️ ${name}`,
    add: '➕ 新建风格',
    chosen: '✅ 你的插图正在使用这个风格。',
    prompt: '风格提示词（点击即可复制）：',
    tailNote: '如果你的文字里没有最后一句，机器人会自动加上：画面中的人物始终是成年人。其余部分完全按你的文字来画。',
    choose: '✅ 用这个风格画',
    sample: '🖼 用最近一幕画示例',
    sampleAll: '🖼 用最近一幕画全部风格',
    edit: '✏️ 修改',
    remove: '🗑 删除',
    back: '↩️ 返回风格列表',
    removeTitle: quotedName => `🗑 删除风格${quotedName}？`,
    removeChosen: name => `你的插图现在正使用它。删除后将改用${name}风格。`,
    removeYes: '🗑 是的，删除',
    removeNo: '↩️ 保留',
    newTitle: '➕ 新的插图风格',
    editTitle: quotedName => `✏️ 风格${quotedName}`,
    inputNote: (max, nameMax) => `用一条消息说明怎么画：技法、色彩、光线、氛围，最多 ${max} 个字符。第一行可以写名称，最多 ${nameMax} 个字符。不用写情节和人物，这些取自场景。插图模型最擅长理解英文。`,
    editNote: max => `用一条消息发来新的文字，最多 ${max} 个字符。第一行可以写新名称，否则保留原来的名称。`,
    example: '例如：',
    exampleText: '烛光油画\nOil painting with visible impasto brushstrokes, warm candlelight and deep shadows.',
    copyHint: '任何风格的提示词都可以从它的卡片上复制下来再修改。',
    nowText: '当前：',
    backToStyle: '↩️ 返回该风格',
    sampleCaption: name => `风格示例：${name}`,
    drawingSample: '🎨 正在绘制示例…',
    // `count` is how many styles are drawn, one picture each.
    drawingAll: (count: number) => `🎨 正在用最近一幕绘制全部 ${count} 种风格。图片会逐张发来；在故事里继续行动会停止绘制。`,
  },

  model: {
    title: '🤖 模型',
    noData: '还没有模型的数据。',
    providers: {
      'claude-code': { short: 'Claude Code', full: 'Claude Code，使用 Claude 订阅（不是我们的 GPU 服务器）' },
      'llama-cpp': { short: '我们的服务器', full: '我们的模型服务器（llama.cpp）' },
      'codex-cli': { short: 'Codex', full: 'Codex CLI，使用 ChatGPT 订阅（不是我们的 GPU 服务器）' },
      'openai-compatible': { short: '托管 API', full: 'OpenAI 格式的托管 API（不是我们的 GPU 服务器）' },
    },
    provider: full => `提供方：${full}`,
    name: model => `模型：${model}`,
    notes: {
      'claude-code': '模型通过 Claude 订阅运行，不在我们租用的 GPU 上。',
      'llama-cpp': '这是我们自己的模型服务器。对它的检查不会测量显卡、GPU 显存、速度和文本质量。',
      'codex-cli': '模型通过 ChatGPT 订阅运行，不在我们租用的 GPU 上。故事文本会发送给第三方服务。',
      'openai-compatible': '模型在第三方提供方那里运行，不在我们租用的 GPU 上。故事文本会发送给第三方服务。',
    },
    ready: time => `✅ 最近一次成功的检查或回复：${time ?? '时间未知'}。`,
    readyNote: '这只代表当时的情况，并非持续监测：模型现在可能已经不再响应。',
    unavailable: time => `⛔ 检查时不可用：${time ?? '时间未知'}。`,
    unavailableNote: '在恢复之前，新场景可能写不出来。',
    configured: '⚪ 已配置但尚未检查，是否就绪还不清楚。',
    unknown: '❔ 状态未知。',
    footer: '模型在机器人的设置里选择，不在聊天里。',
    short: {
      ready: time => (time ? `上次响应 ${time}` : '曾有响应'),
      unavailable: '检查时不可用',
      configured: '尚未检查',
      unknown: '状态未知',
    },
  },

  gpu: {
    title: '🖥 GPU（机器人的所有用户共用）',
    ready: n => `🟢 运行中。当前模型任务：${jobs(n)}。`,
    autoPause: minutes => `自动暂停：连续 ${minutes} 分钟没有模型任务后触发，从最近一次场景或压缩结束时算起。浏览菜单不会重置计时。`,
    untilPause: minutes => `距自动暂停 ≈${minutes} 分钟。`,
    untilPauseSoon: '距自动暂停不到 1 分钟。',
    draining: n => `⏳ 正在暂停：等待所有模型任务结束（当前：${jobs(n)}）。`,
    drainingNote: '暂停前不会开始新的场景和压缩。',
    stopping: '⏳ 正在停止。暂时不会开始新的场景和压缩。',
    paused: '⏸ 已暂停：Vast 已确认停止。',
    pausedNote: '那边不再收取 GPU 运行费用，但磁盘仍在计费。',
    starting: '⏳ 正在启动。可能需要一些时间：要等 Vast 上有空闲显卡，还要等模型预热。',
    error: '⚠️ GPU 控制出错。这不代表它已暂停：它可能仍在运行并计费。点“刷新”。',
    unknown: '❔ GPU 状态未知。这不代表它已暂停或不收费。点“刷新”。',
    pauseHint: '“暂停 GPU”会对所有人停掉它。如果模型正在工作，会等所有场景和压缩结束后再暂停。',
    startHint: '“启动 GPU”同样可能需要一些时间：等空闲显卡和模型预热。',
    storageNote: '故事和存档点保存在机器人这边，暂停不会丢失。',
    start: '▶️ 启动 GPU',
    pause: '⏸ 暂停 GPU',
    short: {
      ready: n => `运行中 · 任务：${jobs(n)}`,
      draining: n => `正在暂停，等待任务：${jobs(n)}`,
      stopping: '正在停止',
      paused: '已暂停',
      starting: '正在启动',
      error: '出错，打开“模型”并刷新',
      unknown: '状态未知，打开“模型”并刷新',
    },
  },

  seeds: {
    title: '📚 种子',
    titleCount: n => `📚 种子：${n}`,
    none: '还没有种子。',
    noStories: '没有故事',
    hint: '选一个种子，开始新故事或打开已开始的故事。',
  },

  seed: {
    notFound: '找不到这个种子。',
    title: name => `🌱 种子${name}`,
    start: time => `故事内开始时间：${time}`,
    startStory: '▶️ 开始新故事',
    stories: n => `📖 这个种子的故事：${n}`,
    story: n => `故事 ${n}`,
    storyButton: n => `📖 故事 ${n}`,
    noStories: '还没有故事。“开始新故事”会创建一个故事，并立刻写出第一个场景。',
    delete: '🗑 删除种子',
    all: '📚 全部种子',
  },

  story: {
    notFound: '找不到这个故事。',
    branches: n => `🌿 分支：${n}`,
    none: '没有分支。',
    hint: '分支是一条独立的事件线。从存档点继续故事时会出现新分支，原来的分支保持不变。',
    tree: '🌳 故事树',
    toSeed: '🌱 返回种子',
  },

  tree: {
    root: '🌱 开端',
    run: (n, until) => `${sceneCount(n)}${until ? `，至 ${until}` : ''}`,
    more: n => `… 还有 ${n} 个`,
    compaction: '🗜 记忆压缩',
    branch: '分支',
    checkpoint: '存档点',
    legend: '🌿 分支 · 🗜 记忆压缩 · 📍 你的存档点 · ✅ 你在这里。没有分岔和标记的一段会折叠成一行；时间为故事内时间。这一段的每个场景都在下方的分支场景列表里。',
    scenes: branch => `📜 场景：${branch}`,
    toStory: '📖 返回故事',
  },

  log: {
    title: name => `📜 分支${name}的场景`,
    summary: n => `${sceneCount(n)}，新的在上`,
    compaction: '🗜 压缩',
    truncated: '⚠️ 中断',
    scene: '场景',
    none: '还没有场景。',
    hint: '打开一个场景来阅读，或从它开一个新分支继续。',
    newer: '⬆️ 较新',
    older: '较早 ⬇️',
    tree: '🌳 故事树',
    toBranch: '🌿 返回分支',
  },

  branch: {
    notFound: '找不到这个分支。',
    title: name => `🌿 分支${name}`,
    isCurrent: '✅ 这是当前分支。',
    lastScene: '最新场景：',
    pickHint: '选这个分支来玩，我会显示它的最新场景。',
    play: '✅ 玩这个分支',
    scenes: '📜 分支的场景',
    checkpoints: n => `🔖 存档点 (${n})`,
    delete: '🗑 删除分支',
    all: '◀️ 全部分支',
  },

  checkpoints: {
    title: (name, n) => `🔖 分支${name}的存档点：${n}`,
    hint: '打开存档点可以重读那个场景，也可以从它开一个新分支继续。新的在上。',
    none: '还没有存档点，每写完一个场景就会出现一个。',
    newer: '⬅️ 较新',
    older: '较早 ➡️',
    toBranch: '◀️ 返回分支',
  },

  checkpoint: {
    notFound: '找不到这个存档点。',
    untitled: '存档点',
    branch: (name, story) => `🌿 分支${name} · ${story}`,
    isHead: '✅ 这是当前分支的最新场景。',
    atStart: '🌱 故事的开端，还没有场景。',
    start: time => `故事内开始时间：${time}`,
    seedMissing: '种子不可用。',
    textMissing: '场景文本不可用。',
    input: text => `✍️ 输入：${text}`,
    truncated: '⚠️ 这个场景在生成时中断了。',
    forkNote: name => `“从这里继续”会从这一刻创建一个新分支。分支${name}保持不变。`,
    fork: '🌿 从这里继续',
    back: '◀️ 存档点',
  },

  context: {
    title: '📏 上下文',
    titleOf: label => `📏 上下文：${label}`,
    checkpoint: '存档点',
    branch: '当前分支',
    none: '📏 上下文：还没有数据。',
    noStory: '还没有选择故事。打开一个种子并选择分支。',
    currentBranch: '📏 当前分支的上下文',
    noData: '还没有上下文大小的数据。',
    noCheckpointData: '还没有这个存档点的大小数据。',
    atCheckpoint: '这是该存档点当时的大小。',
    atBranch: '当前分支，最近一次保存的状态。',
    duringCompaction: '⏳ 正在压缩记忆，这里显示的是压缩前的状态。',
    duringScene: '⏳ 正在写的场景没有计入这里。',
    window: (limit, reserve) => `窗口：${limit} token（含回复）${reserve ? `；为回复预留 ${reserve}` : ''}。`,
    windowUnknown: '窗口：大小未知。',
    nextRequest: (tokens, share) => `下一次请求 ≈${tokens} token${share ? `（≈窗口的 ${share}）` : ''}：快照、机器人规则和一次普通的“继续”。输入较长时还会相应增加。`,
    nextRequestUnknown: '下一次请求：暂无估算。',
    estimateFromUsage: '估算已按这条故事线最近一次实测的请求校准。',
    estimateFromBytes: '粗略估算：UTF-8 字节数 ÷ 4，再加上系统部分的余量。',
    budget: (input, limit) => `输入预算（窗口减去预留）：${input ? `≈${input}` : '未知'} / ${limit} token。`,
    remaining: tokens => `剩余 ≈${tokens} token。`,
    exhausted: '⚠️ 按估算，输入预算已经用完。',
    forecastNote: '这是预测，不是精确计数：模型开始回复时、显示文本之前，还会再检查一次实际输入。',
    autoCompaction: (threshold, keep) => `自动压缩：输入达到 ≈${threshold} token 时触发${keep === null ? '' : `；最近 ${sceneCount(keep)}保留原文`}。`,
    autoCompactionNote: '实测的 token 数可能会修正初步估算。压缩前后都会保存存档点，原始场景留在归档中。',
    snapshot: '快照（B 为精确值；≈ 为 UTF-8 字节数 ÷ 4，并非精确的 token 数）：',
    bytes: n => `${n} B`,
    bytesUnknown: '大小未知',
    tokens: n => `≈${n} token`,
    tokensUnknown: 'token 数未知',
    seed: size => `• 种子：${size}`,
    memory: size => `• 记忆：${size}`,
    memoryEmpty: '空，还没有压缩过',
    prefix: size => `= 种子 + 记忆：${size}`,
    tail: (scenes, size) => `• 未压缩的场景${scenes === null ? '' : `（${scenes}）`}：${size}`,
    whole: size => `= 整个快照：${size}`,
    lastRequest: (input, output, total) => `上一次请求（实测）：输入 ${input} · 输出 ${output} · 合计 ${total}`,
    lastRequestNone: '上一次请求（实测）：暂无数据',
    lastRequestNote: '输入包含缓存部分；输出可能包含模型隐藏的推理。这只是一次请求，不是累计用量，也不是对下一次的预测。',
    compactNote: keep => `🗜 “立即压缩”会把较早的场景概括进记忆，不必等到阈值。${lastScenes(keep)}保留原文，原始场景留在归档中，压缩前后各有一个存档点。压缩不会写新场景。`,
  },

  scenePrefix: {
    context: (percent, rough) => `📏 上下文 ≈ ${percent}%${rough ? '，粗略估算' : ''}`,
    contextBelowOne: rough => `📏 上下文不到 1%${rough ? '，粗略估算' : ''}`,
  },

  deletion: {
    note: '将从机器人保存的故事库中删除，无法恢复。已经发到这个聊天里的消息会保留。',
    seedTitle: name => `🗑 删除种子${name}？`,
    withSeed: '以下内容会一并永久删除：',
    scenesAndCheckpoints: n => `${sceneCount(n)}及所有存档点`,
    includesCurrent: '包括当前故事',
    onlySeed: '这个种子还没有故事，只会删除种子本身。',
    confirmAll: '🗑 是，全部删除',
    confirmSeed: '🗑 是，删除种子',
    branchTitle: name => `🗑 删除分支${name}？`,
    onlyBranch: '这是唯一的分支，所以整个故事都会删除：',
    seedStays: name => `种子${name}会保留，可以用它开始新故事。`,
    forever: '将永久删除：',
    checkpointsOfBranch: n => `这个分支的 ${n} 个存档点`,
    scenesOnlyHere: n => `${n} 个其他分支里没有的场景`,
    scenesStay: '场景会保留：它们在其他分支里都有',
    kept: n => `将保留：这个故事的另外 ${n} 个分支。`,
    isCurrent: '⚠️ 这是当前分支，删除后请另选一个。',
    confirmBranch: '🗑 是，删除分支',
    confirmStory: '🗑 是，删除故事',
  },

  newSeed: {
    title: '➕ 新建种子',
    steps: [
      '用一条或多条消息发来描述：',
      '1) 第一行：标题，不超过 100 个字符；',
      '2) 第二行：故事内的开始日期和时间，格式 YYYY-MM-DD HH:MM（年-月-日 时:分）；',
      '3) 之后：世界、角色和开场情境。',
      '',
      '长文本可以分成几条消息发送：都会合并到同一份草稿里。',
      '📎 也可以附上 .txt / .md 文件（UTF-8，整份草稿不超过 256 KiB）：可以是完整内容，标题和日期写在开头几行；也可以只有描述，这时请先用消息发来标题和日期，再发文件。文件的说明文字不计入，PDF 和 DOCX 不支持。',
      '全部发完后，点“💾 保存种子”。在此之前种子不会保存，也不会写场景。',
    ].join('\n'),
    exampleLabel: '示例：',
    example: [
      '世界尽头的灯塔',
      '2026-08-02 20:00',
      '北方小岛，夏末。米拉，27 岁，今晚是她当灯塔看守人的第一个夜晚。一艘空船漂到码头边，船上的提灯还亮着。',
    ].join('\n'),
    compactRunning: '⏳ 之前开始的记忆压缩还在进行。',
    sceneRunning: '⏳ 之前开始的场景还在写。',
    cancel: '✖️ 取消',
  },

  draft: {
    title: '📝 种子草稿（尚未保存）',
    received: (parts, characters) => `已收到：${parts} 个部分 · ${characters} 个字符`,
    more: '还可以继续发消息或 .txt / .md 文件，它们会追加到描述里。',
    saveHint: '全部发完后，点“💾 保存种子”。现在和保存时都不会写场景，故事可以之后单独开始。',
    menuNote: '保存或放弃草稿后，菜单和其他按钮才会恢复可用。',
    save: '💾 保存种子',
    discard: '🗑 放弃草稿',
  },

  wait: {
    ahead: n => `模型队列中你前面还有 ${n} 个请求。`,
    queued: n => `⏳ 模型队列：你前面还有 ${n} 个请求。`,
    next: '⏳ 轮到你了。',
    reading: '📖 模型正在阅读故事，很快开始写作…',
  },
  compact: {
    title: '🗜 记忆压缩',
    titleAutomatic: '🗜 写新场景前的记忆压缩',
    now: {
      queued: '⏳ 当前：排队等待',
      extracting: '⏳ 当前：模型正在从场景中提取记忆',
      validating: '⏳ 当前：检查记忆结构和对场景的引用',
      saving: '⏳ 当前：保存记忆和存档点',
    },
    steps: { queued: '排队', extracting: '提取', validating: '检查', saving: '保存' },
    elapsed: time => `已用时：${time}`,
    scope: (scenes, kept) => `本次压缩的场景：${scenes} 个；${lastScenes(kept)}不动。`,
    repair: scenes => `↩️ 对遗漏的场景补充提取：${scenes} 个。`,
    memoryJson: characters => `记忆 JSON：${grouped(characters)} 个字符`,
    extraJson: characters => `补充 JSON：${grouped(characters)} 个字符`,
    live: '这条消息会随进度更新。',
    cancelAutomatic: '✖️ 取消',
    done: time => `✅ 压缩完成${time ? ` · ${time}` : ''}`,
    summary: (scenes, facts) => `已概括场景：${scenes} 个，记忆中的事实：${facts} 条。`,
    summaryScenes: scenes => `已概括场景：${scenes} 个。`,
    summaryFacts: facts => `记忆中的事实：${facts} 条。`,
    repaired: scenes => `遗漏的场景（${scenes} 个）已补上，引用检查通过。`,
    kept: kept => `${lastScenes(kept)}保持原样。原始场景已保留，压缩前后都有存档点。`,
    continues: '故事继续：接下来写新场景。',
    failed: time => `⚠️ 压缩失败${time ? ` · ${time}` : ''}`,
    cancelled: time => `✖️ 压缩已取消${time ? ` · ${time}` : ''}`,
    reason: reason => `原因：${reason}。`,
    reasons: {
      output_limit: '概括超出了模型的回复长度上限',
      finish_reason: '模型中途截断了回复',
      json: '模型的回复格式不对',
      shape: '模型的回复没有通过结构检查',
      fact: '有一条事实没有通过检查',
      source: '有一条事实引用了本次压缩之外的场景',
      coverage: '概括没有覆盖所有场景',
      evidence: '对依据的引用没有通过检查',
      quote: '引文在原始场景中找不到',
      conflict: '发现的矛盾没有按规定格式记录',
      memory_not_smaller: '得到的记忆并不比原始场景短',
      provider_failed: '模型不可用或返回了错误',
      timeout: '模型没有及时回复',
      context_limit: '场景放不进模型的上下文',
    },
    safe: '这次尝试得到的记忆没有保存。原始场景和存档点完好无损。',
    retry: command => `重试：${command}`,
    unknown: '压缩状态未知。请查看“上下文”。',
    failure: '无法显示状态。请查看“上下文”。',
  },

  notices: {
    unknownCommand: '我不认识这个命令。打开 /menu 看看。',
    cancelled: '操作已取消。已完成的场景和存档点都已保存。',
    nothingToCompact: keep => `暂时没有可压缩的内容：最近 ${sceneCount(keep)}始终保留原文。不会写新场景。`,
    nothingToCompactYet: keep => `暂时没有可压缩的内容：最近 ${sceneCount(keep)}始终保留原文。`,
    textOnly: '目前只支持文本消息。打开 /menu，或者写下角色的行动。',
    truncated: '回复达到了输出 token 上限，可能被截断。已收到的文本已保存。用 /continue 继续故事。',
    deliveryUnconfirmed: '场景已保存，但未能确认送达。用 /last 查看它，不会重新生成。',
    contextLimit: '种子、累积的记忆、最近的场景或新的输入超出了所选的上下文阈值。所有原始场景和存档点都已保存。可以缩短输入，或通过 /checkpoints 打开另一个存档点。',
    compactionUnverified: command => `无法验证压缩结果。原始场景和已完成的存档点都已保存。重试：${command}。`,
    failed: command => `操作未能完成。已完成的场景和存档点都已保存。重试：${command}。`,
    gpuNotConfigured: '还没有配置 GPU 租用的控制。用 /model 查看当前模型。',
    gpuPaused: 'GPU 已进入暂停。打开 /model 启动它，然后重新发送你的行动。',
    drawing: '🎨 正在绘制插图…',
    pictureFailed: '插图没有画成。场景已保存。',
    sampleFailed: '示例没有画成。请稍后再试。',
  },

  errors: {
    seedFormat: '需要标题（不超过 100 个字符）、格式如 2026-08-02 20:00 的日期，以及对世界的描述，每项另起一行。',
    seedGone: '这个种子已经被删除了。',
    pickBranch: '通过 /seeds 选择一个故事分支。',
    pickStory: '通过 /seeds 选择一个故事或存档点。',
    checkpointGone: '这个存档点已经被删除了。',
    branchGone: '这个分支已经被删除了。',
    branchGoneOpenSeeds: '这个分支已经被删除了。打开 /seeds 看看。',
    jobRunning: '后续内容已经在准备了。如果请求卡住，用 /cancel 取消。',
    sceneTime: '模型没有给出有效的日期和时间。回复没有保存，请把后续再发一次。',
    busy: '已经有生成或压缩在进行。等它回复，或者点 /cancel 后再发一次消息。',
    busyNewSeed: '场景正在写。等它回复，或者点 /cancel 后再创建种子。',
    staleButton: '这个按钮已经过期。打开 /menu 看看。',
    staleConfirmation: '这个确认已经过期。通过 /seeds 重新打开删除页面。',
    gpuNotReady: 'GPU 现在还没准备好。打开 /model 可以启动它或查看状态，然后重新发送你的行动。',
    unsupportedContent: '消息里有不支持的内容。请用不带附件的纯文本发送种子或后续。什么都没有保存。',
    draftChanged: '文件加载期间草稿发生了变化。文件没有添加；打开 /new 后再发一次。',
    otherDraft: '这个按钮属于另一份草稿。请用最后一个已接收部分下方的“保存种子”。',
    draftNeedsText: '请用文本发来种子的下一部分。写完后点“保存种子”。用 /cancel 取消输入。',
    draftTooLarge: '这一部分超出了整份草稿的上限：256 KiB 文本。它没有被添加，之前的部分仍在草稿里。用 /cancel 取消输入。',
    draftClosed: '这份草稿已经保存或放弃。通过 /new 可以创建新种子。',
    fileNeedsDraft: '要用文件上传种子，请先打开 /new。文件没有添加到故事里。',
    fileFailed: '无法读取文件。草稿没有变化，请再发一次文件。',
    fileIncomplete: '无法完整读取文件。草稿没有变化，请再发一次文件。',
    fileTooLarge: '文件太大。单个文件和整份草稿的上限都是 256 KiB 文本。',
    fileType: '请发送 UTF-8 编码的 .txt 或 .md 文本文件。暂不支持 PDF 和 DOCX。',
    fileEncoding: '无法按 UTF-8 读取。请把文件另存为 UTF-8 后再发一次；草稿没有变化。',
    fileBinary: '需要一个非空的 .txt 或 .md 文本文件，且不含二进制数据。草稿没有变化。',
    styleNeedsText: '请用一条文本消息发来风格。不做修改离开：点“↩️”或发送 /cancel。',
    styleTooLong: '太长了：风格不能超过 400 个字符。请缩短后再发一次。',
    stylesFull: '你的风格库里已经有 10 个自定义风格。要新建，请先删除其中一个。',
    sampleOff: '你的场景还没有开启插图，所以无法绘制示例。',
    sampleBusy: '场景还在写。等它发来后再请求示例。',
    sampleNoScene: '示例按你最近的一幕来画。先开始一个故事，第一幕出来后就可以请求示例。',
    sampleInFlight: '正在绘制示例。等它发来后可以再请求下一张。',
  },

  labels: {
    firstBranch: '开端',
    seedCheckpoint: '种子',
    forkBranch: from => `源自：${from}`,
    forkCheckpoint: '分岔点',
    scene: n => `场景 ${n}`,
    beforeCompaction: '压缩前',
    afterCompaction: '压缩后',
  },

  commands: {
    menu: '故事菜单',
    seeds: '我的种子',
    new: '创建种子',
    checkpoints: '场景和存档点',
    continue: '继续故事',
    last: '显示最新场景',
    context: '上下文大小和 token 计数',
    compact: '立即把早期场景压缩进记忆',
    model: '当前模型和连接',
    language: '界面语言',
    style: '场景插图的风格',
    gpu_pause: '任务结束后暂停 GPU',
    gpu_start: '启动租用的 GPU',
    cancel: '取消输入或生成',
  },
};
